language: objective-c
before_install:
  - git submodule sync
  - git submodule update --init
  - gem install xcpretty
install:
  - make gyp
script:
  - make clean
  - make ios
  - make mac
  - make test
