# This file is generated by gyp; do not edit.

include $(CLEAR_VARS)

LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE := libcore_android
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_TARGET_ARCH := $(TARGET_$(GYP_VAR_PREFIX)ARCH)
LOCAL_SDK_VERSION := 19
gyp_intermediate_dir := $(call local-intermediates-dir,,$(GYP_VAR_PREFIX))
gyp_shared_intermediate_dir := $(call intermediates-dir-for,GYP,shared,,,$(GYP_VAR_PREFIX))

# Make sure our deps are built first.
GYP_TARGET_DEPENDENCIES := \
	$(call intermediates-dir-for,STATIC_LIBRARIES,deps_djinni_support_lib_djinni_jni_gyp,,,$(GYP_VAR_PREFIX))/deps_djinni_support_lib_djinni_jni_gyp.a \
	$(call intermediates-dir-for,STATIC_LIBRARIES,libcore_gyp,,,$(GYP_VAR_PREFIX))/libcore_gyp.a \
	$(call intermediates-dir-for,STATIC_LIBRARIES,deps_json11_gyp,,,$(GYP_VAR_PREFIX))/deps_json11_gyp.a \
	$(call intermediates-dir-for,STATIC_LIBRARIES,deps_sqlite3_gyp,,,$(GYP_VAR_PREFIX))/deps_sqlite3_gyp.a \
	$(call intermediates-dir-for,STATIC_LIBRARIES,deps_simpleini_gyp,,,$(GYP_VAR_PREFIX))/deps_simpleini_gyp.a

GYP_GENERATED_OUTPUTS :=

# Make sure our deps and generated files are built first.
LOCAL_ADDITIONAL_DEPENDENCIES := $(GYP_TARGET_DEPENDENCIES) $(GYP_GENERATED_OUTPUTS)

LOCAL_GENERATED_SOURCES :=

GYP_COPIED_SOURCE_ORIGIN_DIRS :=

LOCAL_SRC_FILES := \
	platform/android/jni/jni_main.cpp \
	platform/android/jni_gen/native_api.cpp \
	platform/android/jni_gen/native_async_task.cpp \
	platform/android/jni_gen/native_event_loop.cpp \
	platform/android/jni_gen/native_http.cpp \
	platform/android/jni_gen/native_http_callback.cpp \
	platform/android/jni_gen/native_i_action_callback.cpp \
	platform/android/jni_gen/native_i_contact_table_data_source.cpp \
	platform/android/jni_gen/native_i_contact_ui_controller.cpp \
	platform/android/jni_gen/native_i_contact_view_model.cpp \
	platform/android/jni_gen/native_i_data_change_delegate.cpp \
	platform/android/jni_gen/native_i_data_provider.cpp \
	platform/android/jni_gen/native_i_file_storage_provider.cpp \
	platform/android/jni_gen/native_i_group_callback.cpp \
	platform/android/jni_gen/native_i_group_create_ui_controller.cpp \
	platform/android/jni_gen/native_i_group_detail_ui_controller.cpp \
	platform/android/jni_gen/native_i_group_detail_view_model.cpp \
	platform/android/jni_gen/native_i_group_member_ui_controller.cpp \
	platform/android/jni_gen/native_i_group_member_view_model.cpp \
	platform/android/jni_gen/native_i_group_table_data_source.cpp \
	platform/android/jni_gen/native_i_group_ui_controller.cpp \
	platform/android/jni_gen/native_i_group_update_ui_controller.cpp \
	platform/android/jni_gen/native_i_group_update_view_model.cpp \
	platform/android/jni_gen/native_i_group_view_model.cpp \
	platform/android/jni_gen/native_i_lifecycle_ui_controller.cpp \
	platform/android/jni_gen/native_i_lifecyle_view_model_delegate.cpp \
	platform/android/jni_gen/native_i_log.cpp \
	platform/android/jni_gen/native_i_login_ui_controller.cpp \
	platform/android/jni_gen/native_i_login_view_model.cpp \
	platform/android/jni_gen/native_i_network_callback.cpp \
	platform/android/jni_gen/native_i_network_provider.cpp \
	platform/android/jni_gen/native_i_network_status_delegate.cpp \
	platform/android/jni_gen/native_i_network_status_provider.cpp \
	platform/android/jni_gen/native_i_pal_bundle.cpp \
	platform/android/jni_gen/native_i_profile_ui_controller.cpp \
	platform/android/jni_gen/native_i_profile_view_model.cpp \
	platform/android/jni_gen/native_i_request_upload_token_callback.cpp \
	platform/android/jni_gen/native_i_signup_ui_controller.cpp \
	platform/android/jni_gen/native_i_task.cpp \
	platform/android/jni_gen/native_i_task_dispatcher.cpp \
	platform/android/jni_gen/native_i_ui_controller_factory.cpp \
	platform/android/jni_gen/native_i_view_model_delegate.cpp \
	platform/android/jni_gen/native_i_xplatform_application.cpp \
	platform/android/jni_gen/native_list_change.cpp \
	platform/android/jni_gen/native_r_account.cpp \
	platform/android/jni_gen/native_r_account_response.cpp \
	platform/android/jni_gen/native_r_action_result.cpp \
	platform/android/jni_gen/native_r_avatar_domain.cpp \
	platform/android/jni_gen/native_r_avatar_info.cpp \
	platform/android/jni_gen/native_r_contact.cpp \
	platform/android/jni_gen/native_r_contact_response.cpp \
	platform/android/jni_gen/native_r_future_error.cpp \
	platform/android/jni_gen/native_r_group.cpp \
	platform/android/jni_gen/native_r_group_member.cpp \
	platform/android/jni_gen/native_r_group_response.cpp \
	platform/android/jni_gen/native_r_group_update_response.cpp \
	platform/android/jni_gen/native_r_integer_id_error.cpp \
	platform/android/jni_gen/native_r_network_error.cpp \
	platform/android/jni_gen/native_r_network_request.cpp \
	platform/android/jni_gen/native_r_network_response.cpp \
	platform/android/jni_gen/native_r_parsing_error.cpp \
	platform/android/jni_gen/native_r_server_error.cpp \
	platform/android/jni_gen/native_r_server_error_detail.cpp \
	platform/android/jni_gen/native_r_string_id_error.cpp \
	platform/android/jni_gen/native_r_upload_token.cpp \
	platform/android/jni_gen/native_thread_launcher.cpp \
	platform/android/jni_gen/native_user_list_vm.cpp \
	platform/android/jni_gen/native_user_list_vm_cell.cpp \
	platform/android/jni_gen/native_user_list_vm_handle.cpp \
	platform/android/jni_gen/native_user_list_vm_observer.cpp


# Flags passed to both C and C++ files.
MY_CFLAGS_Debug := \
	-Wall \
	-Wextra \
	-Wno-unused-parameter \
	-fvisibility=hidden \
	-g \
	-O0

MY_DEFS_Debug := \
	'-DDEBUG'


# Include paths placed before CFLAGS/CPPFLAGS
LOCAL_C_INCLUDES_Debug := \
	$(LOCAL_PATH)/include \
	$(LOCAL_PATH)/src/interface \
	$(LOCAL_PATH)/deps \
	$(LOCAL_PATH)/deps/sqlite3 \
	$(LOCAL_PATH)/deps/djinni/support-lib/jni


# Flags passed to only C++ (and not C) files.
LOCAL_CPPFLAGS_Debug := \
	-Wall \
	-Wextra \
	-Wno-unused-parameter \
	-fvisibility=hidden \
	-std=c++1y \
	-fexceptions \
	-frtti


# Flags passed to both C and C++ files.
MY_CFLAGS_Release := \
	-Wall \
	-Wextra \
	-Wno-unused-parameter \
	-fvisibility=hidden \
	-Os \
	-fomit-frame-pointer \
	-fdata-sections \
	-ffunction-sections

MY_DEFS_Release := \
	'-DNDEBUG'


# Include paths placed before CFLAGS/CPPFLAGS
LOCAL_C_INCLUDES_Release := \
	$(LOCAL_PATH)/include \
	$(LOCAL_PATH)/src/interface \
	$(LOCAL_PATH)/deps \
	$(LOCAL_PATH)/deps/sqlite3 \
	$(LOCAL_PATH)/deps/djinni/support-lib/jni


# Flags passed to only C++ (and not C) files.
LOCAL_CPPFLAGS_Release := \
	-Wall \
	-Wextra \
	-Wno-unused-parameter \
	-fvisibility=hidden \
	-std=c++1y \
	-fexceptions \
	-frtti


LOCAL_CFLAGS := $(MY_CFLAGS_$(GYP_CONFIGURATION)) $(MY_DEFS_$(GYP_CONFIGURATION))
LOCAL_C_INCLUDES := $(GYP_COPIED_SOURCE_ORIGIN_DIRS) $(LOCAL_C_INCLUDES_$(GYP_CONFIGURATION))
LOCAL_CPPFLAGS := $(LOCAL_CPPFLAGS_$(GYP_CONFIGURATION))
LOCAL_ASFLAGS := $(LOCAL_CFLAGS)
### Rules for final target.

LOCAL_LDFLAGS_Debug := \
	-llog


LOCAL_LDFLAGS_Release := \
	-llog

LOCAL_GYP_LIBS :=

LOCAL_LDFLAGS := $(LOCAL_LDFLAGS_$(GYP_CONFIGURATION)) $(LOCAL_GYP_LIBS)

LOCAL_STATIC_LIBRARIES := \
	deps_djinni_support_lib_djinni_jni_gyp \
	libcore_gyp \
	deps_json11_gyp \
	deps_sqlite3_gyp \
	deps_simpleini_gyp

# Enable grouping to fix circular references
LOCAL_GROUP_STATIC_LIBRARIES := true
# Add target alias to "gyp_all_modules" target.
.PHONY: gyp_all_modules
gyp_all_modules: libcore_android

LOCAL_PRELINK_MODULE := false
include $(BUILD_SHARED_LIBRARY)
