// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#pragma once

#include <functional>

namespace core_gen {

enum class EErrorType : int {
    SUCCESS,
    NETWORK_FAILURE,
    TIMEOUT,
    SERVER_FAILURE,
    PARSE_FAILURE,
    UNKNOWN,
};

}  // namespace core_gen

namespace std {

template <>
struct hash<::core_gen::EErrorType> {
    size_t operator()(::core_gen::EErrorType type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
