// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#pragma once

#include <functional>

namespace core_gen {

enum class EFutureStatus : int {
    EXECUTING,
    COMPLETE,
    FAILED,
};

}  // namespace core_gen

namespace std {

template <>
struct hash<::core_gen::EFutureStatus> {
    size_t operator()(::core_gen::EFutureStatus type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
