// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

namespace core_gen {

struct RActionResult;

class IActionCallback {
public:
    virtual ~IActionCallback() {}

    virtual void onResponse(const RActionResult & result) = 0;
};

}  // namespace core_gen
