// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include <memory>

namespace core_gen {

class IContactViewModel;

class IContactUiController {
public:
    virtual ~IContactUiController() {}

    virtual std::shared_ptr<IContactViewModel> getViewModel() = 0;
};

}  // namespace core_gen
