// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include <memory>
#include <string>

namespace core_gen {

class IDataChangeDelegate;
struct RContact;
struct RGroup;

class IDataProvider {
public:
    virtual ~IDataProvider() {}

    virtual void setDelegate(const std::shared_ptr<IDataChangeDelegate> & delegate) = 0;

    virtual bool hasContact(const std::string & id) = 0;

    virtual bool hasGroup(const std::string & id) = 0;

    virtual RContact getContact(const std::string & id) = 0;

    virtual RGroup getGroup(const std::string & id) = 0;
};

}  // namespace core_gen
