// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

namespace core_gen {

struct RGroup;

class IGroupDetailViewModel {
public:
    virtual ~IGroupDetailViewModel() {}

    virtual void setGroup(const RGroup & group) = 0;

    virtual RGroup getGroup() = 0;
};

}  // namespace core_gen
