// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include <memory>
#include <vector>

namespace core_gen {

class IGroupCallback;
struct RContact;

class IGroupCreateUiController {
public:
    virtual ~IGroupCreateUiController() {}

    virtual void createGroup(const std::vector<RContact> & contacts, const std::shared_ptr<IGroupCallback> & callback) = 0;
};

}  // namespace core_gen
