// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include <memory>

namespace core_gen {

class IActionCallback;
class IGroupDetailViewModel;
struct RGroup;

class IGroupDetailUiController {
public:
    virtual ~IGroupDetailUiController() {}

    virtual std::shared_ptr<IGroupDetailViewModel> getViewModel() = 0;

    virtual void setGroup(const RGroup & group) = 0;

    virtual void quit(const std::shared_ptr<IActionCallback> & callback) = 0;
};

}  // namespace core_gen
