// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include <memory>

namespace core_gen {

class IGroupTableDataSource;

class IGroupViewModel {
public:
    virtual ~IGroupViewModel() {}

    virtual void setDataSource(const std::shared_ptr<IGroupTableDataSource> & dataSource) = 0;

    virtual std::shared_ptr<IGroupTableDataSource> getDataSource() = 0;
};

}  // namespace core_gen
