// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

namespace core_gen {

struct RAccountResponse;

class ILifecycleUiController {
public:
    virtual ~ILifecycleUiController() {}

    virtual void start() = 0;

    virtual RAccountResponse getAccountInfo() = 0;
};

}  // namespace core_gen
