// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include <string>

namespace core_gen {

enum class ELoginStatus;

/**# login */
class ILoginViewModel {
public:
    virtual ~ILoginViewModel() {}

    virtual std::string getUserName() = 0;

    virtual void setUserName(const std::string & userName) = 0;

    virtual std::string getPassword() = 0;

    virtual void setPassword(const std::string & password) = 0;

    virtual void setStatus(ELoginStatus status) = 0;

    virtual ELoginStatus getStatus() = 0;

    virtual bool isLoading() = 0;

    virtual void setLoading(bool loading) = 0;
};

}  // namespace core_gen
