// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_logger.djinni

#pragma once

#include <string>

namespace core_gen {

enum class LogLevel;

class ILog {
public:
    virtual ~ILog() {}

    virtual void error(const std::string & tag, const std::string & message) = 0;

    virtual void warning(const std::string & tag, const std::string & message) = 0;

    virtual void info(const std::string & tag, const std::string & message) = 0;

    virtual void debug(const std::string & tag, const std::string & message) = 0;

    virtual void verbose(const std::string & tag, const std::string & message) = 0;

    virtual void setLogLevel(LogLevel level) = 0;

    virtual bool visible(LogLevel level) = 0;
};

}  // namespace core_gen
