// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_bundle.djinni

#pragma once

#include <memory>

namespace core_gen {

class IFileStorageProvider;
class ILog;
class INetworkProvider;
class INetworkStatusProvider;
class ITaskDispatcher;

class IPalBundle {
public:
    virtual ~IPalBundle() {}

    virtual std::shared_ptr<INetworkProvider> getNetworkProvider() = 0;

    virtual std::shared_ptr<ILog> getLog() = 0;

    virtual std::shared_ptr<IFileStorageProvider> getFileStorageProvider() = 0;

    virtual std::shared_ptr<INetworkStatusProvider> getNetworkStatusProvider() = 0;

    virtual std::shared_ptr<ITaskDispatcher> getTaskDispatcher() = 0;
};

}  // namespace core_gen
