// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

namespace core_gen {

class IViewModelDelegate {
public:
    virtual ~IViewModelDelegate() {}

    virtual void onDataChanged() = 0;
};

}  // namespace core_gen
