// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from core.djinni

#pragma once

#include <memory>

namespace core_gen {

class IDataProvider;
class IPalBundle;
class IUiControllerFactory;

class IXplatformApplication {
public:
    virtual ~IXplatformApplication() {}

    virtual void initApp(const std::shared_ptr<IPalBundle> & palBundle) = 0;

    static std::shared_ptr<IXplatformApplication> sharedApplication();

    virtual std::shared_ptr<IUiControllerFactory> getUiControllerFactory() = 0;

    virtual std::shared_ptr<IDataProvider> getDataProvider() = 0;
};

}  // namespace core_gen
