// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#pragma once

#include "../network/json/serialization_json.hpp"
#include <optional/optional.hpp> 
#include <string>
#include <utility>

namespace core_gen {

struct RAccount final {

    static std::string const GRAND_TYPE_PASSWORD;
    std::experimental::optional<std::string> username;
    std::experimental::optional<std::string> password;
    std::experimental::optional<std::string> grant_type;
    std::experimental::optional<std::string> id;
    std::experimental::optional<std::string> email;
    std::experimental::optional<std::string> firstName;
    std::experimental::optional<std::string> lastName;
    std::experimental::optional<std::string> displayName;
    std::experimental::optional<std::string> companyId;
    std::experimental::optional<std::string> rongCloudToken;
    std::experimental::optional<std::string> avatarUrl;

    JSON_SERIALIZE("username", username, "password", password, "grant_type", grant_type, "id", id, "email", email, "firstName", firstName, "lastName", lastName, "displayName", displayName, "companyId", companyId, "rongCloudToken", rongCloudToken, "avatarUrl", avatarUrl)

    RAccount(std::experimental::optional<std::string> username_,
             std::experimental::optional<std::string> password_,
             std::experimental::optional<std::string> grant_type_,
             std::experimental::optional<std::string> id_,
             std::experimental::optional<std::string> email_,
             std::experimental::optional<std::string> firstName_,
             std::experimental::optional<std::string> lastName_,
             std::experimental::optional<std::string> displayName_,
             std::experimental::optional<std::string> companyId_,
             std::experimental::optional<std::string> rongCloudToken_,
             std::experimental::optional<std::string> avatarUrl_)
    : username(std::move(username_))
    , password(std::move(password_))
    , grant_type(std::move(grant_type_))
    , id(std::move(id_))
    , email(std::move(email_))
    , firstName(std::move(firstName_))
    , lastName(std::move(lastName_))
    , displayName(std::move(displayName_))
    , companyId(std::move(companyId_))
    , rongCloudToken(std::move(rongCloudToken_))
    , avatarUrl(std::move(avatarUrl_))
    {}
    RAccount() {};
};

}  // namespace core_gen
