// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#pragma once

#include "../network/json/serialization_json.hpp"
#include "r_account.hpp"
#include <cstdint>
#include <optional/optional.hpp> 
#include <string>
#include <utility>

namespace core_gen {

struct RAccountResponse final {
    std::string access_token;
    std::string refresh_token;
    std::experimental::optional<int32_t> expires_in;
    RAccount user;

    JSON_SERIALIZE("access_token", access_token, "refresh_token", refresh_token, "expires_in", expires_in, "user", user)

    RAccountResponse(std::string access_token_,
                     std::string refresh_token_,
                     std::experimental::optional<int32_t> expires_in_,
                     RAccount user_)
    : access_token(std::move(access_token_))
    , refresh_token(std::move(refresh_token_))
    , expires_in(std::move(expires_in_))
    , user(std::move(user_))
    {}
    RAccountResponse() {};
};

}  // namespace core_gen
