// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#pragma once

#include "../network/json/serialization_json.hpp"
#include "r_contact.hpp"
#include <optional/optional.hpp> 
#include <utility>
#include <vector>

namespace core_gen {

struct RContactResponse final {
    std::experimental::optional<std::vector<RContact>> contacts;

    JSON_SERIALIZE("contacts", contacts)

    RContactResponse(std::experimental::optional<std::vector<RContact>> contacts_)
    : contacts(std::move(contacts_))
    {}
    RContactResponse() {};
};

}  // namespace core_gen
