// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#pragma once

#include "e_error_type.hpp"
#include "r_network_error.hpp"
#include "r_parsing_error.hpp"
#include "r_server_error.hpp"
#include <optional/optional.hpp> 
#include <string>
#include <utility>

namespace core_gen {

struct RFutureError final {
    EErrorType type;
    std::experimental::optional<RServerError> serverSrror;
    std::experimental::optional<RParsingError> parsingError;
    std::experimental::optional<RNetworkError> networkError;
    std::experimental::optional<std::string> generalMessage;

    RFutureError(EErrorType type_,
                 std::experimental::optional<RServerError> serverSrror_,
                 std::experimental::optional<RParsingError> parsingError_,
                 std::experimental::optional<RNetworkError> networkError_,
                 std::experimental::optional<std::string> generalMessage_)
    : type(std::move(type_))
    , serverSrror(std::move(serverSrror_))
    , parsingError(std::move(parsingError_))
    , networkError(std::move(networkError_))
    , generalMessage(std::move(generalMessage_))
    {}
    RFutureError() {};
};

}  // namespace core_gen
