// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#pragma once

#include "../model/model.hpp"
#include "e_group_member_type.hpp"
#include <optional/optional.hpp> 
#include <string>
#include <utility>

namespace core_gen {

struct RGroupMember: public Model  {
    std::experimental::optional<std::string> id;
    std::experimental::optional<std::string> groupId;
    std::experimental::optional<std::string> userId;
    std::experimental::optional<EGroupMemberType> type;

    const static std::string ID;
    const static std::string GROUPID;
    const static std::string USERID;
    const static std::string TYPE;


    RGroupMember(std::experimental::optional<std::string> id_,
                 std::experimental::optional<std::string> groupId_,
                 std::experimental::optional<std::string> userId_,
                 std::experimental::optional<EGroupMemberType> type_)
    : id(std::move(id_))
    , groupId(std::move(groupId_))
    , userId(std::move(userId_))
    , type(std::move(type_))
    {}
    RGroupMember() {};
};

}  // namespace core_gen
