// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#include "r_group_member.hpp"  // my header

namespace core_gen {


 std::string const RGroupMember::ID = "id";
 std::string const RGroupMember::GROUPID = "groupId";
 std::string const RGroupMember::USERID = "userId";
 std::string const RGroupMember::TYPE = "type";


}  // namespace core_gen
