// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#pragma once

#include "../network/json/serialization_json.hpp"
#include "r_group.hpp"
#include <optional/optional.hpp> 
#include <utility>
#include <vector>

namespace core_gen {

struct RGroupResponse final {
    std::experimental::optional<std::vector<RGroup>> groups;

    JSON_SERIALIZE("groups", groups)

    RGroupResponse(std::experimental::optional<std::vector<RGroup>> groups_)
    : groups(std::move(groups_))
    {}
    RGroupResponse() {};
};

}  // namespace core_gen
