// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#include "r_group.hpp"  // my header

namespace core_gen {

std::string const RGroup::TYPE_GROUP = {"TeamRoom"};

 std::string const RGroup::ID = "id";
 std::string const RGroup::GROUPNAME = "groupName";
 std::string const RGroup::GROUPTYPE = "groupType";
 std::string const RGroup::USERIDS = "userIds";
 std::string const RGroup::OWNER = "owner";
 std::string const RGroup::ADMIN = "admin";


}  // namespace core_gen
