// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_network_provider.djinni

#pragma once

#include "e_request_result.hpp"
#include <cstdint>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

namespace core_gen {

struct RNetworkResponse final {
    int64_t code;
    std::unordered_map<std::string, std::vector<std::string>> header;
    ERequestResult status;
    std::vector<uint8_t> data;
    std::string content_type;

    RNetworkResponse(int64_t code_,
                     std::unordered_map<std::string, std::vector<std::string>> header_,
                     ERequestResult status_,
                     std::vector<uint8_t> data_,
                     std::string content_type_)
    : code(std::move(code_))
    , header(std::move(header_))
    , status(std::move(status_))
    , data(std::move(data_))
    , content_type(std::move(content_type_))
    {}
    RNetworkResponse() {};
};

}  // namespace core_gen
