// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include <cstdint>
#include <optional/optional.hpp> 

namespace core_gen {

struct UserListVmCell;

class UserListVm {
public:
    virtual ~UserListVm() {}

    /** the total number of results in this list */
    virtual int32_t count() = 0;

    /** get the data for an individual user */
    virtual std::experimental::optional<UserListVmCell> get(int32_t index) = 0;

    /**
     * Delete a row from the view model.  This view model will still remain immutable but a
     * new view model will be sent through the observer interface.
     */
    virtual void delete_row(int32_t index) = 0;
};

}  // namespace core_gen
