// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include <memory>

namespace core_gen {

class UserListVmObserver;

class UserListVmHandle {
public:
    virtual ~UserListVmHandle() {}

    virtual void start(const std::shared_ptr<UserListVmObserver> & observer) = 0;

    virtual void stop() = 0;
};

}  // namespace core_gen
