// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from event_loop.djinni

#pragma once

namespace core_gen {

class AsyncTask {
public:
    virtual ~AsyncTask() {}

    virtual void execute() = 0;
};

}  // namespace core_gen
