// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#pragma once

#include <functional>

namespace core_gen {

enum class EGroupMemberType : int {
    MEMBER,
    OWNER,
    ADMIN,
};

}  // namespace core_gen

namespace std {

template <>
struct hash<::core_gen::EGroupMemberType> {
    size_t operator()(::core_gen::EGroupMemberType type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
