// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#pragma once

#include <functional>

namespace core_gen {

enum class ELoginStatus : int {
    IN_PROGRESS,
    INVALID_CREDENTIALS,
    SUCCESS,
    FAILURE,
};

}  // namespace core_gen

namespace std {

template <>
struct hash<::core_gen::ELoginStatus> {
    size_t operator()(::core_gen::ELoginStatus type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
