// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#pragma once

#include <memory>
#include <string>

namespace core_gen {

class HttpCallback;

class Http {
public:
    virtual ~Http() {}

    virtual void get(const std::string & url, const std::shared_ptr<HttpCallback> & callback) = 0;
};

}  // namespace core_gen
