// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include <memory>
#include <string>

namespace core_gen {

class IGroupCallback;
class IGroupUpdateViewModel;

class IGroupUpdateUiController {
public:
    virtual ~IGroupUpdateUiController() {}

    virtual void updateGroupName(const std::string & groupName, const std::shared_ptr<IGroupCallback> & callback) = 0;

    virtual std::shared_ptr<IGroupUpdateViewModel> getViewModel() = 0;
};

}  // namespace core_gen
