// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include <memory>
#include <string>
#include <vector>

namespace core_gen {

class IGroupCallback;
class IGroupMemberViewModel;
struct RGroup;

class IGroupMemberUiController {
public:
    virtual ~IGroupMemberUiController() {}

    virtual std::shared_ptr<IGroupMemberViewModel> getViewModel() = 0;

    virtual void loadData(const RGroup & group) = 0;

    virtual void addMembers(const std::vector<std::string> & memberIds, const std::shared_ptr<IGroupCallback> & callback) = 0;

    virtual void removeMembers(const std::vector<std::string> & memberIds, const std::shared_ptr<IGroupCallback> & callback) = 0;
};

}  // namespace core_gen
