// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

namespace core_gen {

enum class ECallbackResult;
struct RGroup;

/**#create group */
class IGroupCallback {
public:
    virtual ~IGroupCallback() {}

    virtual void onGroupUpdated(const RGroup & group, ECallbackResult code) = 0;
};

}  // namespace core_gen
