// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include <memory>

namespace core_gen {

class IContactTableDataSource;
struct RGroup;

class IGroupMemberViewModel {
public:
    virtual ~IGroupMemberViewModel() {}

    virtual void setDataSource(const std::shared_ptr<IContactTableDataSource> & dataSource) = 0;

    virtual std::shared_ptr<IContactTableDataSource> getDataSource() = 0;

    virtual void setGroup(const RGroup & group) = 0;

    virtual RGroup getGroup() = 0;
};

}  // namespace core_gen
