// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_network_provider.djinni

#pragma once

#include <memory>

namespace core_gen {

class INetworkStatusDelegate;
enum class ENetworkStatus;

class INetworkStatusProvider {
public:
    virtual ~INetworkStatusProvider() {}

    virtual void setDelegate(const std::shared_ptr<INetworkStatusDelegate> & delegate) = 0;

    virtual ENetworkStatus getNetworkStatus() = 0;

    virtual void startMonitoring() = 0;

    virtual void stopMonitoring() = 0;
};

}  // namespace core_gen
