// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_network_provider.djinni

#pragma once

namespace core_gen {

enum class ENetworkStatus;

class INetworkStatusDelegate {
public:
    virtual ~INetworkStatusDelegate() {}

    virtual void onNetworkStatusChanged(ENetworkStatus status) = 0;
};

}  // namespace core_gen
