// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_network_provider.djinni

#pragma once

#include <cstdint>

namespace core_gen {

struct RNetworkResponse;

class INetworkCallback {
public:
    virtual ~INetworkCallback() {}

    virtual void onSuccess(int64_t requestID, const RNetworkResponse & response) = 0;

    virtual void onFailure(int64_t requestID, const RNetworkResponse & response) = 0;

    /** For uploading/downloading tasks only */
    virtual void onProgress(int64_t requestID, int32_t max_size, int32_t current_pos) = 0;
};

}  // namespace core_gen
