// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include <optional/optional.hpp> 

namespace core_gen {

struct RActionResult;
struct RUploadToken;

/**#profile */
class IRequestUploadTokenCallback {
public:
    virtual ~IRequestUploadTokenCallback() {}

    virtual void onTokenGet(const std::experimental::optional<RUploadToken> & token, const RActionResult & result) = 0;
};

}  // namespace core_gen
