// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include <memory>

namespace core_gen {

class IContactUiController;
class IGroupCreateUiController;
class IGroupDetailUiController;
class IGroupMemberUiController;
class IGroupUiController;
class IGroupUpdateUiController;
class ILifecycleUiController;
class ILifecyleViewModelDelegate;
class ILoginUiController;
class IProfileUiController;
class ISignupUiController;
class IViewModelDelegate;

/**# factory */
class IUiControllerFactory {
public:
    virtual ~IUiControllerFactory() {}

    /** login */
    virtual std::shared_ptr<ILifecycleUiController> createLifecycleUiController(const std::shared_ptr<ILifecyleViewModelDelegate> & delegate) = 0;

    virtual std::shared_ptr<ILoginUiController> createLoginUiController(const std::shared_ptr<IViewModelDelegate> & delegate) = 0;

    virtual std::shared_ptr<ISignupUiController> createSignUpUiController(const std::shared_ptr<IViewModelDelegate> & delegate) = 0;

    /** contact */
    virtual std::shared_ptr<IContactUiController> createContactUiController(const std::shared_ptr<IViewModelDelegate> & delegate) = 0;

    /** group */
    virtual std::shared_ptr<IGroupUiController> createGroupUiController(const std::shared_ptr<IViewModelDelegate> & delegate) = 0;

    virtual std::shared_ptr<IGroupCreateUiController> createGroupCreateUiController(const std::shared_ptr<IViewModelDelegate> & delegate) = 0;

    virtual std::shared_ptr<IGroupUpdateUiController> createGroupUpdateUiController(const std::shared_ptr<IViewModelDelegate> & delegate) = 0;

    virtual std::shared_ptr<IGroupMemberUiController> createGroupMemberUiController(const std::shared_ptr<IViewModelDelegate> & delegate) = 0;

    virtual std::shared_ptr<IGroupDetailUiController> createGroupDetailUiController(const std::shared_ptr<IViewModelDelegate> & delegate) = 0;

    /** profiel */
    virtual std::shared_ptr<IProfileUiController> createProfileUiController(const std::shared_ptr<IViewModelDelegate> & delegate) = 0;
};

}  // namespace core_gen
