// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include <cstdint>
#include <utility>

namespace core_gen {

struct ListChange final {
    int32_t from_index;
    int32_t to_index;

    ListChange(int32_t from_index_,
               int32_t to_index_)
    : from_index(std::move(from_index_))
    , to_index(std::move(to_index_))
    {}
    ListChange() {};
};

}  // namespace core_gen
