// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#pragma once

#include "../network/json/serialization_json.hpp"
#include <optional/optional.hpp> 
#include <string>
#include <utility>

namespace core_gen {

struct RAvatarInfo final {
    std::experimental::optional<std::string> userId;
    std::experimental::optional<std::string> avatarUrl;
    std::experimental::optional<std::string> avatarUploadToken;

    JSON_SERIALIZE("userId", userId, "avatarUrl", avatarUrl, "avatarUploadToken", avatarUploadToken)

    RAvatarInfo(std::experimental::optional<std::string> userId_,
                std::experimental::optional<std::string> avatarUrl_,
                std::experimental::optional<std::string> avatarUploadToken_)
    : userId(std::move(userId_))
    , avatarUrl(std::move(avatarUrl_))
    , avatarUploadToken(std::move(avatarUploadToken_))
    {}
    RAvatarInfo() {};
};

}  // namespace core_gen
