// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#pragma once

#include "../network/json/serialization_json.hpp"
#include <optional/optional.hpp> 
#include <string>
#include <utility>

namespace core_gen {

struct RAvatarDomain final {
    std::experimental::optional<std::string> domain;

    JSON_SERIALIZE("domain", domain)

    RAvatarDomain(std::experimental::optional<std::string> domain_)
    : domain(std::move(domain_))
    {}
    RAvatarDomain() {};
};

}  // namespace core_gen
