// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#include "r_contact.hpp"  // my header

namespace core_gen {


 std::string const RContact::USERNAME = "username";
 std::string const RContact::ID = "id";
 std::string const RContact::EMAIL = "email";
 std::string const RContact::FIRSTNAME = "firstName";
 std::string const RContact::LASTNAME = "lastName";
 std::string const RContact::DISPLAYNAME = "displayName";
 std::string const RContact::COMPANYID = "companyId";
 std::string const RContact::AVATARURL = "avatarUrl";


}  // namespace core_gen
