// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#pragma once

#include "../network/json/serialization_json.hpp"
#include "r_group.hpp"
#include <optional/optional.hpp> 
#include <utility>

namespace core_gen {

struct RGroupUpdateResponse final {
    std::experimental::optional<RGroup> group;

    JSON_SERIALIZE("group", group)

    RGroupUpdateResponse(std::experimental::optional<RGroup> group_)
    : group(std::move(group_))
    {}
    RGroupUpdateResponse() {};
};

}  // namespace core_gen
