// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#pragma once

#include "r_future_error.hpp"
#include <cstdint>
#include <utility>

namespace core_gen {

struct RIntegerIdError final {
    int64_t id;
    RFutureError error;

    RIntegerIdError(int64_t id_,
                    RFutureError error_)
    : id(std::move(id_))
    , error(std::move(error_))
    {}
    RIntegerIdError() {};
};

}  // namespace core_gen
