// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#pragma once

#include "r_server_error_detail.hpp"
#include <optional/optional.hpp> 
#include <string>
#include <utility>
#include <vector>

namespace core_gen {

struct RServerError final {
    std::experimental::optional<std::string> error_code;
    std::experimental::optional<std::string> message;
    std::experimental::optional<std::string> parameterName;
    std::experimental::optional<std::string> parameter;
    std::vector<RServerErrorDetail> errors;
    std::experimental::optional<std::string> error;
    std::experimental::optional<std::string> errorDescription;

    RServerError(std::experimental::optional<std::string> error_code_,
                 std::experimental::optional<std::string> message_,
                 std::experimental::optional<std::string> parameterName_,
                 std::experimental::optional<std::string> parameter_,
                 std::vector<RServerErrorDetail> errors_,
                 std::experimental::optional<std::string> error_,
                 std::experimental::optional<std::string> errorDescription_)
    : error_code(std::move(error_code_))
    , message(std::move(message_))
    , parameterName(std::move(parameterName_))
    , parameter(std::move(parameter_))
    , errors(std::move(errors_))
    , error(std::move(error_))
    , errorDescription(std::move(errorDescription_))
    {}
    RServerError() {};
};

}  // namespace core_gen
