// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#pragma once

#include "r_future_error.hpp"
#include <string>
#include <utility>

namespace core_gen {

struct RStringIdError final {
    std::string id;
    RFutureError error;

    RStringIdError(std::string id_,
                   RFutureError error_)
    : id(std::move(id_))
    , error(std::move(error_))
    {}
    RStringIdError() {};
};

}  // namespace core_gen
