// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from future.djinni

#pragma once

#include "../../interface/r_future_error.hpp"
#include <functional>
#include <memory>
#include <vector>

namespace core {
    
    template<typename Type>
    class IFutureCallback : public std::enable_shared_from_this<IFutureCallback<Type>> {
    public:
        virtual ~IFutureCallback() {}
        virtual void callback(std::shared_ptr<Type> value, std::shared_ptr<RFutureError> error) = 0;
        std::function<void(std::shared_ptr<Type>, std::shared_ptr<RFutureError>, std::shared_ptr<std::vector<uint8_t>>)> createWrapper() {
            auto _this = this->shared_from_this();
            return [_this](std::shared_ptr<Type> v, std::shared_ptr<RFutureError> e, std::shared_ptr<std::vector<uint8_t>> b) {
                _this->callback(v, e);
            };
        }
    };
    
}
