// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_network_provider.djinni

#pragma once

#include "djinni_support.hpp"
#include "e_network_status.hpp"

namespace djinni_generated {

class NativeENetworkStatus final : ::djinni::JniEnum {
public:
    using CppType = ::core_gen::ENetworkStatus;
    using JniType = jobject;

    using Boxed = NativeENetworkStatus;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeENetworkStatus>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeENetworkStatus>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeENetworkStatus() : JniEnum("com/nextuc/ENetworkStatus") {}
    friend ::djinni::JniClass<NativeENetworkStatus>;
};

}  // namespace djinni_generated
