// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include "djinni_support.hpp"
#include "i_profile_view_model.hpp"

namespace djinni_generated {

class NativeIProfileViewModel final : ::djinni::JniInterface<::core_gen::IProfileViewModel, NativeIProfileViewModel> {
public:
    using CppType = std::shared_ptr<::core_gen::IProfileViewModel>;
    using CppOptType = std::shared_ptr<::core_gen::IProfileViewModel>;
    using JniType = jobject;

    using Boxed = NativeIProfileViewModel;

    ~NativeIProfileViewModel();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeIProfileViewModel>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeIProfileViewModel>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeIProfileViewModel();
    friend ::djinni::JniClass<NativeIProfileViewModel>;
    friend ::djinni::JniInterface<::core_gen::IProfileViewModel, NativeIProfileViewModel>;

};

}  // namespace djinni_generated
