// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#pragma once

#include "djinni_support.hpp"
#include "r_avatar_domain.hpp"

namespace djinni_generated {

class NativeRAvatarDomain final {
public:
    using CppType = ::core_gen::RAvatarDomain;
    using JniType = jobject;

    using Boxed = NativeRAvatarDomain;

    ~NativeRAvatarDomain();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeRAvatarDomain();
    friend ::djinni::JniClass<NativeRAvatarDomain>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/nextuc/RAvatarDomain") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;)V") };
    const jfieldID field_mDomain { ::djinni::jniGetFieldID(clazz.get(), "mDomain", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
