// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#include "native_r_group_response.hpp"  // my header
#include "Marshal.hpp"
#include "native_r_group.hpp"

namespace djinni_generated {

NativeRGroupResponse::NativeRGroupResponse() = default;

NativeRGroupResponse::~NativeRGroupResponse() = default;

auto NativeRGroupResponse::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeRGroupResponse>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::Optional<std::experimental::optional, ::djinni::List<::djinni_generated::NativeRGroup>>::fromCpp(jniEnv, c.groups)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeRGroupResponse::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 2);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeRGroupResponse>::get();
    return {::djinni::Optional<std::experimental::optional, ::djinni::List<::djinni_generated::NativeRGroup>>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mGroups))};
}

}  // namespace djinni_generated
