// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from core.djinni

#pragma once

#include "djinni_support.hpp"
#include "i_xplatform_application.hpp"

namespace djinni_generated {

class NativeIXplatformApplication final : ::djinni::JniInterface<::core_gen::IXplatformApplication, NativeIXplatformApplication> {
public:
    using CppType = std::shared_ptr<::core_gen::IXplatformApplication>;
    using CppOptType = std::shared_ptr<::core_gen::IXplatformApplication>;
    using JniType = jobject;

    using Boxed = NativeIXplatformApplication;

    ~NativeIXplatformApplication();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeIXplatformApplication>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeIXplatformApplication>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeIXplatformApplication();
    friend ::djinni::JniClass<NativeIXplatformApplication>;
    friend ::djinni::JniInterface<::core_gen::IXplatformApplication, NativeIXplatformApplication>;

};

}  // namespace djinni_generated
