// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#pragma once

#include "djinni_support.hpp"
#include "e_group_member_type.hpp"

namespace djinni_generated {

class NativeEGroupMemberType final : ::djinni::JniEnum {
public:
    using CppType = ::core_gen::EGroupMemberType;
    using JniType = jobject;

    using Boxed = NativeEGroupMemberType;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeEGroupMemberType>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeEGroupMemberType>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeEGroupMemberType() : JniEnum("com/nextuc/EGroupMemberType") {}
    friend ::djinni::JniClass<NativeEGroupMemberType>;
};

}  // namespace djinni_generated
