// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#include "native_i_lifecycle_ui_controller.hpp"  // my header
#include "native_r_account_response.hpp"

namespace djinni_generated {

NativeILifecycleUiController::NativeILifecycleUiController() : ::djinni::JniInterface<::core_gen::ILifecycleUiController, NativeILifecycleUiController>("com/nextuc/ILifecycleUiController$CppProxy") {}

NativeILifecycleUiController::~NativeILifecycleUiController() = default;


CJNIEXPORT void JNICALL Java_com_nextuc_ILifecycleUiController_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<djinni::CppProxyHandle<::core_gen::ILifecycleUiController>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_nextuc_ILifecycleUiController_00024CppProxy_native_1start(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::core_gen::ILifecycleUiController>(nativeRef);
        ref->start();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_nextuc_ILifecycleUiController_00024CppProxy_native_1getAccountInfo(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::core_gen::ILifecycleUiController>(nativeRef);
        auto r = ref->getAccountInfo();
        return ::djinni::release(::djinni_generated::NativeRAccountResponse::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
