// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#include "native_r_group_update_response.hpp"  // my header
#include "Marshal.hpp"
#include "native_r_group.hpp"

namespace djinni_generated {

NativeRGroupUpdateResponse::NativeRGroupUpdateResponse() = default;

NativeRGroupUpdateResponse::~NativeRGroupUpdateResponse() = default;

auto NativeRGroupUpdateResponse::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeRGroupUpdateResponse>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::Optional<std::experimental::optional, ::djinni_generated::NativeRGroup>::fromCpp(jniEnv, c.group)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeRGroupUpdateResponse::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 2);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeRGroupUpdateResponse>::get();
    return {::djinni::Optional<std::experimental::optional, ::djinni_generated::NativeRGroup>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mGroup))};
}

}  // namespace djinni_generated
