// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_network_provider.djinni

#pragma once

#include "djinni_support.hpp"
#include "i_network_callback.hpp"

namespace djinni_generated {

class NativeINetworkCallback final : ::djinni::JniInterface<::core_gen::INetworkCallback, NativeINetworkCallback> {
public:
    using CppType = std::shared_ptr<::core_gen::INetworkCallback>;
    using CppOptType = std::shared_ptr<::core_gen::INetworkCallback>;
    using JniType = jobject;

    using Boxed = NativeINetworkCallback;

    ~NativeINetworkCallback();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeINetworkCallback>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeINetworkCallback>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeINetworkCallback();
    friend ::djinni::JniClass<NativeINetworkCallback>;
    friend ::djinni::JniInterface<::core_gen::INetworkCallback, NativeINetworkCallback>;

};

}  // namespace djinni_generated
