// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include "djinni_support.hpp"
#include "i_group_member_ui_controller.hpp"

namespace djinni_generated {

class NativeIGroupMemberUiController final : ::djinni::JniInterface<::core_gen::IGroupMemberUiController, NativeIGroupMemberUiController> {
public:
    using CppType = std::shared_ptr<::core_gen::IGroupMemberUiController>;
    using CppOptType = std::shared_ptr<::core_gen::IGroupMemberUiController>;
    using JniType = jobject;

    using Boxed = NativeIGroupMemberUiController;

    ~NativeIGroupMemberUiController();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeIGroupMemberUiController>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeIGroupMemberUiController>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeIGroupMemberUiController();
    friend ::djinni::JniClass<NativeIGroupMemberUiController>;
    friend ::djinni::JniInterface<::core_gen::IGroupMemberUiController, NativeIGroupMemberUiController>;

};

}  // namespace djinni_generated
