// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#pragma once

#include "djinni_support.hpp"
#include "r_contact_response.hpp"

namespace djinni_generated {

class NativeRContactResponse final {
public:
    using CppType = ::core_gen::RContactResponse;
    using JniType = jobject;

    using Boxed = NativeRContactResponse;

    ~NativeRContactResponse();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeRContactResponse();
    friend ::djinni::JniClass<NativeRContactResponse>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/nextuc/RContactResponse") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/util/ArrayList;)V") };
    const jfieldID field_mContacts { ::djinni::jniGetFieldID(clazz.get(), "mContacts", "Ljava/util/ArrayList;") };
};

}  // namespace djinni_generated
