// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from thread.djinni

#include "native_thread_launcher.hpp"  // my header
#include "Marshal.hpp"
#include "native_async_task.hpp"

namespace djinni_generated {

NativeThreadLauncher::NativeThreadLauncher() : ::djinni::JniInterface<::core_gen::ThreadLauncher, NativeThreadLauncher>() {}

NativeThreadLauncher::~NativeThreadLauncher() = default;

NativeThreadLauncher::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeThreadLauncher::JavaProxy::~JavaProxy() = default;

void NativeThreadLauncher::JavaProxy::start_thread(const std::experimental::optional<std::string> & c_name, const std::shared_ptr<::core_gen::AsyncTask> & c_run_fn) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeThreadLauncher>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_startThread,
                           ::djinni::get(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(jniEnv, c_name)),
                           ::djinni::get(::djinni_generated::NativeAsyncTask::fromCpp(jniEnv, c_run_fn)));
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
