// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include "djinni_support.hpp"
#include "i_group_view_model.hpp"

namespace djinni_generated {

class NativeIGroupViewModel final : ::djinni::JniInterface<::core_gen::IGroupViewModel, NativeIGroupViewModel> {
public:
    using CppType = std::shared_ptr<::core_gen::IGroupViewModel>;
    using CppOptType = std::shared_ptr<::core_gen::IGroupViewModel>;
    using JniType = jobject;

    using Boxed = NativeIGroupViewModel;

    ~NativeIGroupViewModel();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeIGroupViewModel>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeIGroupViewModel>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeIGroupViewModel();
    friend ::djinni::JniClass<NativeIGroupViewModel>;
    friend ::djinni::JniInterface<::core_gen::IGroupViewModel, NativeIGroupViewModel>;

};

}  // namespace djinni_generated
