// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include "djinni_support.hpp"
#include "i_data_change_delegate.hpp"

namespace djinni_generated {

class NativeIDataChangeDelegate final : ::djinni::JniInterface<::core_gen::IDataChangeDelegate, NativeIDataChangeDelegate> {
public:
    using CppType = std::shared_ptr<::core_gen::IDataChangeDelegate>;
    using CppOptType = std::shared_ptr<::core_gen::IDataChangeDelegate>;
    using JniType = jobject;

    using Boxed = NativeIDataChangeDelegate;

    ~NativeIDataChangeDelegate();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeIDataChangeDelegate>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeIDataChangeDelegate>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeIDataChangeDelegate();
    friend ::djinni::JniClass<NativeIDataChangeDelegate>;
    friend ::djinni::JniInterface<::core_gen::IDataChangeDelegate, NativeIDataChangeDelegate>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::core_gen::IDataChangeDelegate
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void onContactChanged(const ::core_gen::RContact & contact) override;
        void onGroupChanged(const ::core_gen::RGroup & group) override;

    private:
        friend ::djinni::JniInterface<::core_gen::IDataChangeDelegate, ::djinni_generated::NativeIDataChangeDelegate>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/nextuc/IDataChangeDelegate") };
    const jmethodID method_onContactChanged { ::djinni::jniGetMethodID(clazz.get(), "onContactChanged", "(Lcom/nextuc/RContact;)V") };
    const jmethodID method_onGroupChanged { ::djinni::jniGetMethodID(clazz.get(), "onGroupChanged", "(Lcom/nextuc/RGroup;)V") };
};

}  // namespace djinni_generated
