// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#pragma once

#include "djinni_support.hpp"
#include "r_server_error_detail.hpp"

namespace djinni_generated {

class NativeRServerErrorDetail final {
public:
    using CppType = ::core_gen::RServerErrorDetail;
    using JniType = jobject;

    using Boxed = NativeRServerErrorDetail;

    ~NativeRServerErrorDetail();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeRServerErrorDetail();
    friend ::djinni::JniClass<NativeRServerErrorDetail>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/nextuc/RServerErrorDetail") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V") };
    const jfieldID field_mErrorCode { ::djinni::jniGetFieldID(clazz.get(), "mErrorCode", "Ljava/lang/String;") };
    const jfieldID field_mMessage { ::djinni::jniGetFieldID(clazz.get(), "mMessage", "Ljava/lang/String;") };
    const jfieldID field_mParameter { ::djinni::jniGetFieldID(clazz.get(), "mParameter", "Ljava/lang/String;") };
    const jfieldID field_mParameterName { ::djinni::jniGetFieldID(clazz.get(), "mParameterName", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
