// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_network_provider.djinni

#include "native_r_network_response.hpp"  // my header
#include "Marshal.hpp"
#include "native_e_request_result.hpp"

namespace djinni_generated {

NativeRNetworkResponse::NativeRNetworkResponse() = default;

NativeRNetworkResponse::~NativeRNetworkResponse() = default;

auto NativeRNetworkResponse::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeRNetworkResponse>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.code)),
                                                           ::djinni::get(::djinni::Map<::djinni::String, ::djinni::List<::djinni::String>>::fromCpp(jniEnv, c.header)),
                                                           ::djinni::get(::djinni_generated::NativeERequestResult::fromCpp(jniEnv, c.status)),
                                                           ::djinni::get(::djinni::Binary::fromCpp(jniEnv, c.data)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.content_type)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeRNetworkResponse::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 6);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeRNetworkResponse>::get();
    return {::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_mCode)),
            ::djinni::Map<::djinni::String, ::djinni::List<::djinni::String>>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mHeader)),
            ::djinni_generated::NativeERequestResult::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mStatus)),
            ::djinni::Binary::toCpp(jniEnv, (jbyteArray)jniEnv->GetObjectField(j, data.field_mData)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mContentType))};
}

}  // namespace djinni_generated
