// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from thread.djinni

#pragma once

#include "djinni_support.hpp"
#include "thread_launcher.hpp"

namespace djinni_generated {

class NativeThreadLauncher final : ::djinni::JniInterface<::core_gen::ThreadLauncher, NativeThreadLauncher> {
public:
    using CppType = std::shared_ptr<::core_gen::ThreadLauncher>;
    using CppOptType = std::shared_ptr<::core_gen::ThreadLauncher>;
    using JniType = jobject;

    using Boxed = NativeThreadLauncher;

    ~NativeThreadLauncher();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeThreadLauncher>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeThreadLauncher>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeThreadLauncher();
    friend ::djinni::JniClass<NativeThreadLauncher>;
    friend ::djinni::JniInterface<::core_gen::ThreadLauncher, NativeThreadLauncher>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::core_gen::ThreadLauncher
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void start_thread(const std::experimental::optional<std::string> & name, const std::shared_ptr<::core_gen::AsyncTask> & run_fn) override;

    private:
        friend ::djinni::JniInterface<::core_gen::ThreadLauncher, ::djinni_generated::NativeThreadLauncher>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/nextuc/ThreadLauncher") };
    const jmethodID method_startThread { ::djinni::jniGetMethodID(clazz.get(), "startThread", "(Ljava/lang/String;Lcom/nextuc/AsyncTask;)V") };
};

}  // namespace djinni_generated
