// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#include "native_i_group_detail_ui_controller.hpp"  // my header
#include "native_i_action_callback.hpp"
#include "native_i_group_detail_view_model.hpp"
#include "native_r_group.hpp"

namespace djinni_generated {

NativeIGroupDetailUiController::NativeIGroupDetailUiController() : ::djinni::JniInterface<::core_gen::IGroupDetailUiController, NativeIGroupDetailUiController>("com/nextuc/IGroupDetailUiController$CppProxy") {}

NativeIGroupDetailUiController::~NativeIGroupDetailUiController() = default;


CJNIEXPORT void JNICALL Java_com_nextuc_IGroupDetailUiController_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<djinni::CppProxyHandle<::core_gen::IGroupDetailUiController>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_nextuc_IGroupDetailUiController_00024CppProxy_native_1getViewModel(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::core_gen::IGroupDetailUiController>(nativeRef);
        auto r = ref->getViewModel();
        return ::djinni::release(::djinni_generated::NativeIGroupDetailViewModel::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_nextuc_IGroupDetailUiController_00024CppProxy_native_1setGroup(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_group)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::core_gen::IGroupDetailUiController>(nativeRef);
        ref->setGroup(::djinni_generated::NativeRGroup::toCpp(jniEnv, j_group));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_nextuc_IGroupDetailUiController_00024CppProxy_native_1quit(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_callback)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::core_gen::IGroupDetailUiController>(nativeRef);
        ref->quit(::djinni_generated::NativeIActionCallback::toCpp(jniEnv, j_callback));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
