// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include "djinni_support.hpp"
#include "i_view_model_delegate.hpp"

namespace djinni_generated {

class NativeIViewModelDelegate final : ::djinni::JniInterface<::core_gen::IViewModelDelegate, NativeIViewModelDelegate> {
public:
    using CppType = std::shared_ptr<::core_gen::IViewModelDelegate>;
    using CppOptType = std::shared_ptr<::core_gen::IViewModelDelegate>;
    using JniType = jobject;

    using Boxed = NativeIViewModelDelegate;

    ~NativeIViewModelDelegate();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeIViewModelDelegate>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeIViewModelDelegate>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeIViewModelDelegate();
    friend ::djinni::JniClass<NativeIViewModelDelegate>;
    friend ::djinni::JniInterface<::core_gen::IViewModelDelegate, NativeIViewModelDelegate>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::core_gen::IViewModelDelegate
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void onDataChanged() override;

    private:
        friend ::djinni::JniInterface<::core_gen::IViewModelDelegate, ::djinni_generated::NativeIViewModelDelegate>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/nextuc/IViewModelDelegate") };
    const jmethodID method_onDataChanged { ::djinni::jniGetMethodID(clazz.get(), "onDataChanged", "()V") };
};

}  // namespace djinni_generated
