// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#pragma once

#include "djinni_support.hpp"
#include "r_network_error.hpp"

namespace djinni_generated {

class NativeRNetworkError final {
public:
    using CppType = ::core_gen::RNetworkError;
    using JniType = jobject;

    using Boxed = NativeRNetworkError;

    ~NativeRNetworkError();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeRNetworkError();
    friend ::djinni::JniClass<NativeRNetworkError>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/nextuc/RNetworkError") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(I)V") };
    const jfieldID field_mErrorCode { ::djinni::jniGetFieldID(clazz.get(), "mErrorCode", "I") };
};

}  // namespace djinni_generated
