// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include "djinni_support.hpp"
#include "i_group_member_view_model.hpp"

namespace djinni_generated {

class NativeIGroupMemberViewModel final : ::djinni::JniInterface<::core_gen::IGroupMemberViewModel, NativeIGroupMemberViewModel> {
public:
    using CppType = std::shared_ptr<::core_gen::IGroupMemberViewModel>;
    using CppOptType = std::shared_ptr<::core_gen::IGroupMemberViewModel>;
    using JniType = jobject;

    using Boxed = NativeIGroupMemberViewModel;

    ~NativeIGroupMemberViewModel();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeIGroupMemberViewModel>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeIGroupMemberViewModel>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeIGroupMemberViewModel();
    friend ::djinni::JniClass<NativeIGroupMemberViewModel>;
    friend ::djinni::JniInterface<::core_gen::IGroupMemberViewModel, NativeIGroupMemberViewModel>;

};

}  // namespace djinni_generated
