// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#pragma once

#include "djinni_support.hpp"
#include "r_contact.hpp"

namespace djinni_generated {

class NativeRContact final {
public:
    using CppType = ::core_gen::RContact;
    using JniType = jobject;

    using Boxed = NativeRContact;

    ~NativeRContact();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeRContact();
    friend ::djinni::JniClass<NativeRContact>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/nextuc/RContact") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V") };
    const jfieldID field_mUsername { ::djinni::jniGetFieldID(clazz.get(), "mUsername", "Ljava/lang/String;") };
    const jfieldID field_mId { ::djinni::jniGetFieldID(clazz.get(), "mId", "Ljava/lang/String;") };
    const jfieldID field_mEmail { ::djinni::jniGetFieldID(clazz.get(), "mEmail", "Ljava/lang/String;") };
    const jfieldID field_mFirstName { ::djinni::jniGetFieldID(clazz.get(), "mFirstName", "Ljava/lang/String;") };
    const jfieldID field_mLastName { ::djinni::jniGetFieldID(clazz.get(), "mLastName", "Ljava/lang/String;") };
    const jfieldID field_mDisplayName { ::djinni::jniGetFieldID(clazz.get(), "mDisplayName", "Ljava/lang/String;") };
    const jfieldID field_mCompanyId { ::djinni::jniGetFieldID(clazz.get(), "mCompanyId", "Ljava/lang/String;") };
    const jfieldID field_mAvatarUrl { ::djinni::jniGetFieldID(clazz.get(), "mAvatarUrl", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
