// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#include "native_r_avatar_domain.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeRAvatarDomain::NativeRAvatarDomain() = default;

NativeRAvatarDomain::~NativeRAvatarDomain() = default;

auto NativeRAvatarDomain::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeRAvatarDomain>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(jniEnv, c.domain)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeRAvatarDomain::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 2);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeRAvatarDomain>::get();
    return {::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mDomain))};
}

}  // namespace djinni_generated
