// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#pragma once

#include "djinni_support.hpp"
#include "http.hpp"

namespace djinni_generated {

class NativeHttp final : ::djinni::JniInterface<::core_gen::Http, NativeHttp> {
public:
    using CppType = std::shared_ptr<::core_gen::Http>;
    using CppOptType = std::shared_ptr<::core_gen::Http>;
    using JniType = jobject;

    using Boxed = NativeHttp;

    ~NativeHttp();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeHttp>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeHttp>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeHttp();
    friend ::djinni::JniClass<NativeHttp>;
    friend ::djinni::JniInterface<::core_gen::Http, NativeHttp>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::core_gen::Http
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void get(const std::string & url, const std::shared_ptr<::core_gen::HttpCallback> & callback) override;

    private:
        friend ::djinni::JniInterface<::core_gen::Http, ::djinni_generated::NativeHttp>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/nextuc/Http") };
    const jmethodID method_get { ::djinni::jniGetMethodID(clazz.get(), "get", "(Ljava/lang/String;Lcom/nextuc/HttpCallback;)V") };
};

}  // namespace djinni_generated
