// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include "djinni_support.hpp"
#include "i_group_detail_view_model.hpp"

namespace djinni_generated {

class NativeIGroupDetailViewModel final : ::djinni::JniInterface<::core_gen::IGroupDetailViewModel, NativeIGroupDetailViewModel> {
public:
    using CppType = std::shared_ptr<::core_gen::IGroupDetailViewModel>;
    using CppOptType = std::shared_ptr<::core_gen::IGroupDetailViewModel>;
    using JniType = jobject;

    using Boxed = NativeIGroupDetailViewModel;

    ~NativeIGroupDetailViewModel();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeIGroupDetailViewModel>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeIGroupDetailViewModel>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeIGroupDetailViewModel();
    friend ::djinni::JniClass<NativeIGroupDetailViewModel>;
    friend ::djinni::JniInterface<::core_gen::IGroupDetailViewModel, NativeIGroupDetailViewModel>;

};

}  // namespace djinni_generated
