// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#include "native_i_group_view_model.hpp"  // my header
#include "native_i_group_table_data_source.hpp"

namespace djinni_generated {

NativeIGroupViewModel::NativeIGroupViewModel() : ::djinni::JniInterface<::core_gen::IGroupViewModel, NativeIGroupViewModel>("com/nextuc/IGroupViewModel$CppProxy") {}

NativeIGroupViewModel::~NativeIGroupViewModel() = default;


CJNIEXPORT void JNICALL Java_com_nextuc_IGroupViewModel_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<djinni::CppProxyHandle<::core_gen::IGroupViewModel>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_nextuc_IGroupViewModel_00024CppProxy_native_1setDataSource(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_dataSource)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::core_gen::IGroupViewModel>(nativeRef);
        ref->setDataSource(::djinni_generated::NativeIGroupTableDataSource::toCpp(jniEnv, j_dataSource));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_nextuc_IGroupViewModel_00024CppProxy_native_1getDataSource(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::core_gen::IGroupViewModel>(nativeRef);
        auto r = ref->getDataSource();
        return ::djinni::release(::djinni_generated::NativeIGroupTableDataSource::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
