// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include "djinni_support.hpp"
#include "i_group_ui_controller.hpp"

namespace djinni_generated {

class NativeIGroupUiController final : ::djinni::JniInterface<::core_gen::IGroupUiController, NativeIGroupUiController> {
public:
    using CppType = std::shared_ptr<::core_gen::IGroupUiController>;
    using CppOptType = std::shared_ptr<::core_gen::IGroupUiController>;
    using JniType = jobject;

    using Boxed = NativeIGroupUiController;

    ~NativeIGroupUiController();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeIGroupUiController>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeIGroupUiController>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeIGroupUiController();
    friend ::djinni::JniClass<NativeIGroupUiController>;
    friend ::djinni::JniInterface<::core_gen::IGroupUiController, NativeIGroupUiController>;

};

}  // namespace djinni_generated
