// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#pragma once

#include "djinni_support.hpp"
#include "r_parsing_error.hpp"

namespace djinni_generated {

class NativeRParsingError final {
public:
    using CppType = ::core_gen::RParsingError;
    using JniType = jobject;

    using Boxed = NativeRParsingError;

    ~NativeRParsingError();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeRParsingError();
    friend ::djinni::JniClass<NativeRParsingError>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/nextuc/RParsingError") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;)V") };
    const jfieldID field_mMessage { ::djinni::jniGetFieldID(clazz.get(), "mMessage", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
