// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#include "native_i_profile_view_model.hpp"  // my header
#include "native_r_account.hpp"

namespace djinni_generated {

NativeIProfileViewModel::NativeIProfileViewModel() : ::djinni::JniInterface<::core_gen::IProfileViewModel, NativeIProfileViewModel>("com/nextuc/IProfileViewModel$CppProxy") {}

NativeIProfileViewModel::~NativeIProfileViewModel() = default;


CJNIEXPORT void JNICALL Java_com_nextuc_IProfileViewModel_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<djinni::CppProxyHandle<::core_gen::IProfileViewModel>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_nextuc_IProfileViewModel_00024CppProxy_native_1setAccount(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_account)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::core_gen::IProfileViewModel>(nativeRef);
        ref->setAccount(::djinni_generated::NativeRAccount::toCpp(jniEnv, j_account));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_nextuc_IProfileViewModel_00024CppProxy_native_1getAccount(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::core_gen::IProfileViewModel>(nativeRef);
        auto r = ref->getAccount();
        return ::djinni::release(::djinni_generated::NativeRAccount::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
