// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_network_provider.djinni

#pragma once

#include "djinni_support.hpp"
#include "i_network_provider.hpp"

namespace djinni_generated {

class NativeINetworkProvider final : ::djinni::JniInterface<::core_gen::INetworkProvider, NativeINetworkProvider> {
public:
    using CppType = std::shared_ptr<::core_gen::INetworkProvider>;
    using CppOptType = std::shared_ptr<::core_gen::INetworkProvider>;
    using JniType = jobject;

    using Boxed = NativeINetworkProvider;

    ~NativeINetworkProvider();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeINetworkProvider>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeINetworkProvider>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeINetworkProvider();
    friend ::djinni::JniClass<NativeINetworkProvider>;
    friend ::djinni::JniInterface<::core_gen::INetworkProvider, NativeINetworkProvider>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::core_gen::INetworkProvider
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void request(const ::core_gen::RNetworkRequest & request, const std::shared_ptr<::core_gen::INetworkCallback> & callback) override;

    private:
        friend ::djinni::JniInterface<::core_gen::INetworkProvider, ::djinni_generated::NativeINetworkProvider>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/nextuc/INetworkProvider") };
    const jmethodID method_request { ::djinni::jniGetMethodID(clazz.get(), "request", "(Lcom/nextuc/RNetworkRequest;Lcom/nextuc/INetworkCallback;)V") };
};

}  // namespace djinni_generated
