// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#pragma once

#include "djinni_support.hpp"
#include "e_login_status.hpp"

namespace djinni_generated {

class NativeELoginStatus final : ::djinni::JniEnum {
public:
    using CppType = ::core_gen::ELoginStatus;
    using JniType = jobject;

    using Boxed = NativeELoginStatus;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeELoginStatus>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeELoginStatus>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeELoginStatus() : JniEnum("com/nextuc/ELoginStatus") {}
    friend ::djinni::JniClass<NativeELoginStatus>;
};

}  // namespace djinni_generated
