// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#pragma once

#include "djinni_support.hpp"
#include "e_future_status.hpp"

namespace djinni_generated {

class NativeEFutureStatus final : ::djinni::JniEnum {
public:
    using CppType = ::core_gen::EFutureStatus;
    using JniType = jobject;

    using Boxed = NativeEFutureStatus;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeEFutureStatus>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeEFutureStatus>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeEFutureStatus() : JniEnum("com/nextuc/EFutureStatus") {}
    friend ::djinni::JniClass<NativeEFutureStatus>;
};

}  // namespace djinni_generated
