// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include "djinni_support.hpp"
#include "i_contact_table_data_source.hpp"

namespace djinni_generated {

class NativeIContactTableDataSource final : ::djinni::JniInterface<::core_gen::IContactTableDataSource, NativeIContactTableDataSource> {
public:
    using CppType = std::shared_ptr<::core_gen::IContactTableDataSource>;
    using CppOptType = std::shared_ptr<::core_gen::IContactTableDataSource>;
    using JniType = jobject;

    using Boxed = NativeIContactTableDataSource;

    ~NativeIContactTableDataSource();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeIContactTableDataSource>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeIContactTableDataSource>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeIContactTableDataSource();
    friend ::djinni::JniClass<NativeIContactTableDataSource>;
    friend ::djinni::JniInterface<::core_gen::IContactTableDataSource, NativeIContactTableDataSource>;

};

}  // namespace djinni_generated
