// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include "djinni_support.hpp"
#include "i_ui_controller_factory.hpp"

namespace djinni_generated {

class NativeIUiControllerFactory final : ::djinni::JniInterface<::core_gen::IUiControllerFactory, NativeIUiControllerFactory> {
public:
    using CppType = std::shared_ptr<::core_gen::IUiControllerFactory>;
    using CppOptType = std::shared_ptr<::core_gen::IUiControllerFactory>;
    using JniType = jobject;

    using Boxed = NativeIUiControllerFactory;

    ~NativeIUiControllerFactory();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeIUiControllerFactory>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeIUiControllerFactory>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeIUiControllerFactory();
    friend ::djinni::JniClass<NativeIUiControllerFactory>;
    friend ::djinni::JniInterface<::core_gen::IUiControllerFactory, NativeIUiControllerFactory>;

};

}  // namespace djinni_generated
