// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#include "native_i_group_member_view_model.hpp"  // my header
#include "native_i_contact_table_data_source.hpp"
#include "native_r_group.hpp"

namespace djinni_generated {

NativeIGroupMemberViewModel::NativeIGroupMemberViewModel() : ::djinni::JniInterface<::core_gen::IGroupMemberViewModel, NativeIGroupMemberViewModel>("com/nextuc/IGroupMemberViewModel$CppProxy") {}

NativeIGroupMemberViewModel::~NativeIGroupMemberViewModel() = default;


CJNIEXPORT void JNICALL Java_com_nextuc_IGroupMemberViewModel_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<djinni::CppProxyHandle<::core_gen::IGroupMemberViewModel>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_nextuc_IGroupMemberViewModel_00024CppProxy_native_1setDataSource(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_dataSource)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::core_gen::IGroupMemberViewModel>(nativeRef);
        ref->setDataSource(::djinni_generated::NativeIContactTableDataSource::toCpp(jniEnv, j_dataSource));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_nextuc_IGroupMemberViewModel_00024CppProxy_native_1getDataSource(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::core_gen::IGroupMemberViewModel>(nativeRef);
        auto r = ref->getDataSource();
        return ::djinni::release(::djinni_generated::NativeIContactTableDataSource::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_nextuc_IGroupMemberViewModel_00024CppProxy_native_1setGroup(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_group)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::core_gen::IGroupMemberViewModel>(nativeRef);
        ref->setGroup(::djinni_generated::NativeRGroup::toCpp(jniEnv, j_group));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_nextuc_IGroupMemberViewModel_00024CppProxy_native_1getGroup(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::core_gen::IGroupMemberViewModel>(nativeRef);
        auto r = ref->getGroup();
        return ::djinni::release(::djinni_generated::NativeRGroup::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
