// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include "djinni_support.hpp"
#include "i_group_create_ui_controller.hpp"

namespace djinni_generated {

class NativeIGroupCreateUiController final : ::djinni::JniInterface<::core_gen::IGroupCreateUiController, NativeIGroupCreateUiController> {
public:
    using CppType = std::shared_ptr<::core_gen::IGroupCreateUiController>;
    using CppOptType = std::shared_ptr<::core_gen::IGroupCreateUiController>;
    using JniType = jobject;

    using Boxed = NativeIGroupCreateUiController;

    ~NativeIGroupCreateUiController();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeIGroupCreateUiController>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeIGroupCreateUiController>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeIGroupCreateUiController();
    friend ::djinni::JniClass<NativeIGroupCreateUiController>;
    friend ::djinni::JniInterface<::core_gen::IGroupCreateUiController, NativeIGroupCreateUiController>;

};

}  // namespace djinni_generated
