// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include "djinni_support.hpp"
#include "i_profile_ui_controller.hpp"

namespace djinni_generated {

class NativeIProfileUiController final : ::djinni::JniInterface<::core_gen::IProfileUiController, NativeIProfileUiController> {
public:
    using CppType = std::shared_ptr<::core_gen::IProfileUiController>;
    using CppOptType = std::shared_ptr<::core_gen::IProfileUiController>;
    using JniType = jobject;

    using Boxed = NativeIProfileUiController;

    ~NativeIProfileUiController();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeIProfileUiController>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeIProfileUiController>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeIProfileUiController();
    friend ::djinni::JniClass<NativeIProfileUiController>;
    friend ::djinni::JniInterface<::core_gen::IProfileUiController, NativeIProfileUiController>;

};

}  // namespace djinni_generated
