// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#include "native_user_list_vm_handle.hpp"  // my header
#include "native_user_list_vm_observer.hpp"

namespace djinni_generated {

NativeUserListVmHandle::NativeUserListVmHandle() : ::djinni::JniInterface<::core_gen::UserListVmHandle, NativeUserListVmHandle>("com/nextuc/UserListVmHandle$CppProxy") {}

NativeUserListVmHandle::~NativeUserListVmHandle() = default;


CJNIEXPORT void JNICALL Java_com_nextuc_UserListVmHandle_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<djinni::CppProxyHandle<::core_gen::UserListVmHandle>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_nextuc_UserListVmHandle_00024CppProxy_native_1start(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_observer)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::core_gen::UserListVmHandle>(nativeRef);
        ref->start(::djinni_generated::NativeUserListVmObserver::toCpp(jniEnv, j_observer));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_nextuc_UserListVmHandle_00024CppProxy_native_1stop(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::core_gen::UserListVmHandle>(nativeRef);
        ref->stop();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
