// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from event_loop.djinni

#pragma once

#include "djinni_support.hpp"
#include "event_loop.hpp"

namespace djinni_generated {

class NativeEventLoop final : ::djinni::JniInterface<::core_gen::EventLoop, NativeEventLoop> {
public:
    using CppType = std::shared_ptr<::core_gen::EventLoop>;
    using CppOptType = std::shared_ptr<::core_gen::EventLoop>;
    using JniType = jobject;

    using Boxed = NativeEventLoop;

    ~NativeEventLoop();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeEventLoop>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeEventLoop>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeEventLoop();
    friend ::djinni::JniClass<NativeEventLoop>;
    friend ::djinni::JniInterface<::core_gen::EventLoop, NativeEventLoop>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::core_gen::EventLoop
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void post(const std::shared_ptr<::core_gen::AsyncTask> & task) override;

    private:
        friend ::djinni::JniInterface<::core_gen::EventLoop, ::djinni_generated::NativeEventLoop>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/nextuc/EventLoop") };
    const jmethodID method_post { ::djinni::jniGetMethodID(clazz.get(), "post", "(Lcom/nextuc/AsyncTask;)V") };
};

}  // namespace djinni_generated
