// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include "djinni_support.hpp"
#include "list_change.hpp"

namespace djinni_generated {

class NativeListChange final {
public:
    using CppType = ::core_gen::ListChange;
    using JniType = jobject;

    using Boxed = NativeListChange;

    ~NativeListChange();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeListChange();
    friend ::djinni::JniClass<NativeListChange>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/nextuc/ListChange") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(II)V") };
    const jfieldID field_mFromIndex { ::djinni::jniGetFieldID(clazz.get(), "mFromIndex", "I") };
    const jfieldID field_mToIndex { ::djinni::jniGetFieldID(clazz.get(), "mToIndex", "I") };
};

}  // namespace djinni_generated
