// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#include "native_i_group_create_ui_controller.hpp"  // my header
#include "Marshal.hpp"
#include "native_i_group_callback.hpp"
#include "native_r_contact.hpp"

namespace djinni_generated {

NativeIGroupCreateUiController::NativeIGroupCreateUiController() : ::djinni::JniInterface<::core_gen::IGroupCreateUiController, NativeIGroupCreateUiController>("com/nextuc/IGroupCreateUiController$CppProxy") {}

NativeIGroupCreateUiController::~NativeIGroupCreateUiController() = default;


CJNIEXPORT void JNICALL Java_com_nextuc_IGroupCreateUiController_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<djinni::CppProxyHandle<::core_gen::IGroupCreateUiController>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_nextuc_IGroupCreateUiController_00024CppProxy_native_1createGroup(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_contacts, jobject j_callback)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::core_gen::IGroupCreateUiController>(nativeRef);
        ref->createGroup(::djinni::List<::djinni_generated::NativeRContact>::toCpp(jniEnv, j_contacts),
                         ::djinni_generated::NativeIGroupCallback::toCpp(jniEnv, j_callback));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
