// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from core.djinni

#include "native_i_xplatform_application.hpp"  // my header
#include "native_i_data_provider.hpp"
#include "native_i_pal_bundle.hpp"
#include "native_i_ui_controller_factory.hpp"
#include "native_i_xplatform_application.hpp"

namespace djinni_generated {

NativeIXplatformApplication::NativeIXplatformApplication() : ::djinni::JniInterface<::core_gen::IXplatformApplication, NativeIXplatformApplication>("com/nextuc/IXplatformApplication$CppProxy") {}

NativeIXplatformApplication::~NativeIXplatformApplication() = default;


CJNIEXPORT void JNICALL Java_com_nextuc_IXplatformApplication_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<djinni::CppProxyHandle<::core_gen::IXplatformApplication>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_nextuc_IXplatformApplication_00024CppProxy_native_1initApp(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_palBundle)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::core_gen::IXplatformApplication>(nativeRef);
        ref->initApp(::djinni_generated::NativeIPalBundle::toCpp(jniEnv, j_palBundle));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_nextuc_IXplatformApplication_sharedApplication(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::core_gen::IXplatformApplication::sharedApplication();
        return ::djinni::release(::djinni_generated::NativeIXplatformApplication::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_nextuc_IXplatformApplication_00024CppProxy_native_1getUiControllerFactory(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::core_gen::IXplatformApplication>(nativeRef);
        auto r = ref->getUiControllerFactory();
        return ::djinni::release(::djinni_generated::NativeIUiControllerFactory::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_nextuc_IXplatformApplication_00024CppProxy_native_1getDataProvider(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::core_gen::IXplatformApplication>(nativeRef);
        auto r = ref->getDataProvider();
        return ::djinni::release(::djinni_generated::NativeIDataProvider::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
