// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#include "native_i_group_member_ui_controller.hpp"  // my header
#include "Marshal.hpp"
#include "native_i_group_callback.hpp"
#include "native_i_group_member_view_model.hpp"
#include "native_r_group.hpp"

namespace djinni_generated {

NativeIGroupMemberUiController::NativeIGroupMemberUiController() : ::djinni::JniInterface<::core_gen::IGroupMemberUiController, NativeIGroupMemberUiController>("com/nextuc/IGroupMemberUiController$CppProxy") {}

NativeIGroupMemberUiController::~NativeIGroupMemberUiController() = default;


CJNIEXPORT void JNICALL Java_com_nextuc_IGroupMemberUiController_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<djinni::CppProxyHandle<::core_gen::IGroupMemberUiController>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_nextuc_IGroupMemberUiController_00024CppProxy_native_1getViewModel(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::core_gen::IGroupMemberUiController>(nativeRef);
        auto r = ref->getViewModel();
        return ::djinni::release(::djinni_generated::NativeIGroupMemberViewModel::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_nextuc_IGroupMemberUiController_00024CppProxy_native_1loadData(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_group)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::core_gen::IGroupMemberUiController>(nativeRef);
        ref->loadData(::djinni_generated::NativeRGroup::toCpp(jniEnv, j_group));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_nextuc_IGroupMemberUiController_00024CppProxy_native_1addMembers(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_memberIds, jobject j_callback)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::core_gen::IGroupMemberUiController>(nativeRef);
        ref->addMembers(::djinni::List<::djinni::String>::toCpp(jniEnv, j_memberIds),
                        ::djinni_generated::NativeIGroupCallback::toCpp(jniEnv, j_callback));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_nextuc_IGroupMemberUiController_00024CppProxy_native_1removeMembers(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_memberIds, jobject j_callback)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::core_gen::IGroupMemberUiController>(nativeRef);
        ref->removeMembers(::djinni::List<::djinni::String>::toCpp(jniEnv, j_memberIds),
                           ::djinni_generated::NativeIGroupCallback::toCpp(jniEnv, j_callback));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
