// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_network_provider.djinni

#include "native_i_network_status_delegate.hpp"  // my header
#include "native_e_network_status.hpp"

namespace djinni_generated {

NativeINetworkStatusDelegate::NativeINetworkStatusDelegate() : ::djinni::JniInterface<::core_gen::INetworkStatusDelegate, NativeINetworkStatusDelegate>("com/nextuc/INetworkStatusDelegate$CppProxy") {}

NativeINetworkStatusDelegate::~NativeINetworkStatusDelegate() = default;


CJNIEXPORT void JNICALL Java_com_nextuc_INetworkStatusDelegate_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<djinni::CppProxyHandle<::core_gen::INetworkStatusDelegate>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_nextuc_INetworkStatusDelegate_00024CppProxy_native_1onNetworkStatusChanged(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_status)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::core_gen::INetworkStatusDelegate>(nativeRef);
        ref->onNetworkStatusChanged(::djinni_generated::NativeENetworkStatus::toCpp(jniEnv, j_status));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
