// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#include "native_i_group_callback.hpp"  // my header
#include "native_e_callback_result.hpp"
#include "native_r_group.hpp"

namespace djinni_generated {

NativeIGroupCallback::NativeIGroupCallback() : ::djinni::JniInterface<::core_gen::IGroupCallback, NativeIGroupCallback>() {}

NativeIGroupCallback::~NativeIGroupCallback() = default;

NativeIGroupCallback::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeIGroupCallback::JavaProxy::~JavaProxy() = default;

void NativeIGroupCallback::JavaProxy::onGroupUpdated(const ::core_gen::RGroup & c_group, ::core_gen::ECallbackResult c_code) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeIGroupCallback>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onGroupUpdated,
                           ::djinni::get(::djinni_generated::NativeRGroup::fromCpp(jniEnv, c_group)),
                           ::djinni::get(::djinni_generated::NativeECallbackResult::fromCpp(jniEnv, c_code)));
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
