// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#pragma once

#include "djinni_support.hpp"
#include "e_account_status.hpp"

namespace djinni_generated {

class NativeEAccountStatus final : ::djinni::JniEnum {
public:
    using CppType = ::core_gen::EAccountStatus;
    using JniType = jobject;

    using Boxed = NativeEAccountStatus;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeEAccountStatus>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeEAccountStatus>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeEAccountStatus() : JniEnum("com/nextuc/EAccountStatus") {}
    friend ::djinni::JniClass<NativeEAccountStatus>;
};

}  // namespace djinni_generated
