// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#pragma once

#include "djinni_support.hpp"
#include "e_error_type.hpp"

namespace djinni_generated {

class NativeEErrorType final : ::djinni::JniEnum {
public:
    using CppType = ::core_gen::EErrorType;
    using JniType = jobject;

    using Boxed = NativeEErrorType;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeEErrorType>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeEErrorType>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeEErrorType() : JniEnum("com/nextuc/EErrorType") {}
    friend ::djinni::JniClass<NativeEErrorType>;
};

}  // namespace djinni_generated
