// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#pragma once

#include "djinni_support.hpp"
#include "r_integer_id_error.hpp"

namespace djinni_generated {

class NativeRIntegerIdError final {
public:
    using CppType = ::core_gen::RIntegerIdError;
    using JniType = jobject;

    using Boxed = NativeRIntegerIdError;

    ~NativeRIntegerIdError();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeRIntegerIdError();
    friend ::djinni::JniClass<NativeRIntegerIdError>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/nextuc/RIntegerIdError") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(JLcom/nextuc/RFutureError;)V") };
    const jfieldID field_mId { ::djinni::jniGetFieldID(clazz.get(), "mId", "J") };
    const jfieldID field_mError { ::djinni::jniGetFieldID(clazz.get(), "mError", "Lcom/nextuc/RFutureError;") };
};

}  // namespace djinni_generated
