// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#include "native_i_signup_ui_controller.hpp"  // my header
#include "Marshal.hpp"
#include "native_i_action_callback.hpp"

namespace djinni_generated {

NativeISignupUiController::NativeISignupUiController() : ::djinni::JniInterface<::core_gen::ISignupUiController, NativeISignupUiController>("com/nextuc/ISignupUiController$CppProxy") {}

NativeISignupUiController::~NativeISignupUiController() = default;


CJNIEXPORT void JNICALL Java_com_nextuc_ISignupUiController_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<djinni::CppProxyHandle<::core_gen::ISignupUiController>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_nextuc_ISignupUiController_00024CppProxy_native_1signup(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_userName, jstring j_password, jstring j_firstName, jstring j_lastName, jobject j_callback)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::core_gen::ISignupUiController>(nativeRef);
        ref->signup(::djinni::String::toCpp(jniEnv, j_userName),
                    ::djinni::String::toCpp(jniEnv, j_password),
                    ::djinni::String::toCpp(jniEnv, j_firstName),
                    ::djinni::String::toCpp(jniEnv, j_lastName),
                    ::djinni_generated::NativeIActionCallback::toCpp(jniEnv, j_callback));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
