// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#pragma once

#include "djinni_support.hpp"
#include "r_group_response.hpp"

namespace djinni_generated {

class NativeRGroupResponse final {
public:
    using CppType = ::core_gen::RGroupResponse;
    using JniType = jobject;

    using Boxed = NativeRGroupResponse;

    ~NativeRGroupResponse();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeRGroupResponse();
    friend ::djinni::JniClass<NativeRGroupResponse>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/nextuc/RGroupResponse") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/util/ArrayList;)V") };
    const jfieldID field_mGroups { ::djinni::jniGetFieldID(clazz.get(), "mGroups", "Ljava/util/ArrayList;") };
};

}  // namespace djinni_generated
