// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#pragma once

#include "djinni_support.hpp"
#include "r_upload_token.hpp"

namespace djinni_generated {

class NativeRUploadToken final {
public:
    using CppType = ::core_gen::RUploadToken;
    using JniType = jobject;

    using Boxed = NativeRUploadToken;

    ~NativeRUploadToken();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeRUploadToken();
    friend ::djinni::JniClass<NativeRUploadToken>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/nextuc/RUploadToken") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;Ljava/lang/String;)V") };
    const jfieldID field_mUserId { ::djinni::jniGetFieldID(clazz.get(), "mUserId", "Ljava/lang/String;") };
    const jfieldID field_mAvatarUploadToken { ::djinni::jniGetFieldID(clazz.get(), "mAvatarUploadToken", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
