// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#include "native_i_contact_view_model.hpp"  // my header
#include "native_i_contact_table_data_source.hpp"

namespace djinni_generated {

NativeIContactViewModel::NativeIContactViewModel() : ::djinni::JniInterface<::core_gen::IContactViewModel, NativeIContactViewModel>("com/nextuc/IContactViewModel$CppProxy") {}

NativeIContactViewModel::~NativeIContactViewModel() = default;


CJNIEXPORT void JNICALL Java_com_nextuc_IContactViewModel_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<djinni::CppProxyHandle<::core_gen::IContactViewModel>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_nextuc_IContactViewModel_00024CppProxy_native_1setDataSource(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_dataSource)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::core_gen::IContactViewModel>(nativeRef);
        ref->setDataSource(::djinni_generated::NativeIContactTableDataSource::toCpp(jniEnv, j_dataSource));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_nextuc_IContactViewModel_00024CppProxy_native_1getDataSource(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::core_gen::IContactViewModel>(nativeRef);
        auto r = ref->getDataSource();
        return ::djinni::release(::djinni_generated::NativeIContactTableDataSource::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
