// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#include "native_i_view_model_delegate.hpp"  // my header

namespace djinni_generated {

NativeIViewModelDelegate::NativeIViewModelDelegate() : ::djinni::JniInterface<::core_gen::IViewModelDelegate, NativeIViewModelDelegate>() {}

NativeIViewModelDelegate::~NativeIViewModelDelegate() = default;

NativeIViewModelDelegate::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeIViewModelDelegate::JavaProxy::~JavaProxy() = default;

void NativeIViewModelDelegate::JavaProxy::onDataChanged() {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeIViewModelDelegate>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onDataChanged);
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
