// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_task_dispatcher.djinni

#pragma once

#include "djinni_support.hpp"
#include "i_task.hpp"

namespace djinni_generated {

class NativeITask final : ::djinni::JniInterface<::core_gen::ITask, NativeITask> {
public:
    using CppType = std::shared_ptr<::core_gen::ITask>;
    using CppOptType = std::shared_ptr<::core_gen::ITask>;
    using JniType = jobject;

    using Boxed = NativeITask;

    ~NativeITask();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeITask>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeITask>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeITask();
    friend ::djinni::JniClass<NativeITask>;
    friend ::djinni::JniInterface<::core_gen::ITask, NativeITask>;

};

}  // namespace djinni_generated
