// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#include "native_list_change.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeListChange::NativeListChange() = default;

NativeListChange::~NativeListChange() = default;

auto NativeListChange::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeListChange>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.from_index)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.to_index)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeListChange::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 3);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeListChange>::get();
    return {::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mFromIndex)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mToIndex))};
}

}  // namespace djinni_generated
