// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_network_provider.djinni

#pragma once

#include "djinni_support.hpp"
#include "e_network_method.hpp"

namespace djinni_generated {

class NativeENetworkMethod final : ::djinni::JniEnum {
public:
    using CppType = ::core_gen::ENetworkMethod;
    using JniType = jobject;

    using Boxed = NativeENetworkMethod;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeENetworkMethod>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeENetworkMethod>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeENetworkMethod() : JniEnum("com/nextuc/ENetworkMethod") {}
    friend ::djinni::JniClass<NativeENetworkMethod>;
};

}  // namespace djinni_generated
