// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_network_provider.djinni

#pragma once

#include "djinni_support.hpp"
#include "e_request_type.hpp"

namespace djinni_generated {

class NativeERequestType final : ::djinni::JniEnum {
public:
    using CppType = ::core_gen::ERequestType;
    using JniType = jobject;

    using Boxed = NativeERequestType;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeERequestType>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeERequestType>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeERequestType() : JniEnum("com/nextuc/ERequestType") {}
    friend ::djinni::JniClass<NativeERequestType>;
};

}  // namespace djinni_generated
