// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#pragma once

#include "djinni_support.hpp"
#include "r_account.hpp"

namespace djinni_generated {

class NativeRAccount final {
public:
    using CppType = ::core_gen::RAccount;
    using JniType = jobject;

    using Boxed = NativeRAccount;

    ~NativeRAccount();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeRAccount();
    friend ::djinni::JniClass<NativeRAccount>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/nextuc/RAccount") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V") };
    const jfieldID field_mUsername { ::djinni::jniGetFieldID(clazz.get(), "mUsername", "Ljava/lang/String;") };
    const jfieldID field_mPassword { ::djinni::jniGetFieldID(clazz.get(), "mPassword", "Ljava/lang/String;") };
    const jfieldID field_mGrantType { ::djinni::jniGetFieldID(clazz.get(), "mGrantType", "Ljava/lang/String;") };
    const jfieldID field_mId { ::djinni::jniGetFieldID(clazz.get(), "mId", "Ljava/lang/String;") };
    const jfieldID field_mEmail { ::djinni::jniGetFieldID(clazz.get(), "mEmail", "Ljava/lang/String;") };
    const jfieldID field_mFirstName { ::djinni::jniGetFieldID(clazz.get(), "mFirstName", "Ljava/lang/String;") };
    const jfieldID field_mLastName { ::djinni::jniGetFieldID(clazz.get(), "mLastName", "Ljava/lang/String;") };
    const jfieldID field_mDisplayName { ::djinni::jniGetFieldID(clazz.get(), "mDisplayName", "Ljava/lang/String;") };
    const jfieldID field_mCompanyId { ::djinni::jniGetFieldID(clazz.get(), "mCompanyId", "Ljava/lang/String;") };
    const jfieldID field_mRongCloudToken { ::djinni::jniGetFieldID(clazz.get(), "mRongCloudToken", "Ljava/lang/String;") };
    const jfieldID field_mAvatarUrl { ::djinni::jniGetFieldID(clazz.get(), "mAvatarUrl", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
