// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from event_loop.djinni

#include "native_async_task.hpp"  // my header

namespace djinni_generated {

NativeAsyncTask::NativeAsyncTask() : ::djinni::JniInterface<::core_gen::AsyncTask, NativeAsyncTask>("com/nextuc/AsyncTask$CppProxy") {}

NativeAsyncTask::~NativeAsyncTask() = default;


CJNIEXPORT void JNICALL Java_com_nextuc_AsyncTask_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<djinni::CppProxyHandle<::core_gen::AsyncTask>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_nextuc_AsyncTask_00024CppProxy_native_1execute(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::core_gen::AsyncTask>(nativeRef);
        ref->execute();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
