// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#include "native_r_future_error.hpp"  // my header
#include "Marshal.hpp"
#include "native_e_error_type.hpp"
#include "native_r_network_error.hpp"
#include "native_r_parsing_error.hpp"
#include "native_r_server_error.hpp"

namespace djinni_generated {

NativeRFutureError::NativeRFutureError() = default;

NativeRFutureError::~NativeRFutureError() = default;

auto NativeRFutureError::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeRFutureError>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni_generated::NativeEErrorType::fromCpp(jniEnv, c.type)),
                                                           ::djinni::get(::djinni::Optional<std::experimental::optional, ::djinni_generated::NativeRServerError>::fromCpp(jniEnv, c.serverSrror)),
                                                           ::djinni::get(::djinni::Optional<std::experimental::optional, ::djinni_generated::NativeRParsingError>::fromCpp(jniEnv, c.parsingError)),
                                                           ::djinni::get(::djinni::Optional<std::experimental::optional, ::djinni_generated::NativeRNetworkError>::fromCpp(jniEnv, c.networkError)),
                                                           ::djinni::get(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(jniEnv, c.generalMessage)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeRFutureError::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 6);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeRFutureError>::get();
    return {::djinni_generated::NativeEErrorType::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mType)),
            ::djinni::Optional<std::experimental::optional, ::djinni_generated::NativeRServerError>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mServerSrror)),
            ::djinni::Optional<std::experimental::optional, ::djinni_generated::NativeRParsingError>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mParsingError)),
            ::djinni::Optional<std::experimental::optional, ::djinni_generated::NativeRNetworkError>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mNetworkError)),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mGeneralMessage))};
}

}  // namespace djinni_generated
