// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include "djinni_support.hpp"
#include "user_list_vm.hpp"

namespace djinni_generated {

class NativeUserListVm final : ::djinni::JniInterface<::core_gen::UserListVm, NativeUserListVm> {
public:
    using CppType = std::shared_ptr<::core_gen::UserListVm>;
    using CppOptType = std::shared_ptr<::core_gen::UserListVm>;
    using JniType = jobject;

    using Boxed = NativeUserListVm;

    ~NativeUserListVm();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeUserListVm>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeUserListVm>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeUserListVm();
    friend ::djinni::JniClass<NativeUserListVm>;
    friend ::djinni::JniInterface<::core_gen::UserListVm, NativeUserListVm>;

};

}  // namespace djinni_generated
