// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include "djinni_support.hpp"
#include "i_group_callback.hpp"

namespace djinni_generated {

class NativeIGroupCallback final : ::djinni::JniInterface<::core_gen::IGroupCallback, NativeIGroupCallback> {
public:
    using CppType = std::shared_ptr<::core_gen::IGroupCallback>;
    using CppOptType = std::shared_ptr<::core_gen::IGroupCallback>;
    using JniType = jobject;

    using Boxed = NativeIGroupCallback;

    ~NativeIGroupCallback();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeIGroupCallback>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeIGroupCallback>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeIGroupCallback();
    friend ::djinni::JniClass<NativeIGroupCallback>;
    friend ::djinni::JniInterface<::core_gen::IGroupCallback, NativeIGroupCallback>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::core_gen::IGroupCallback
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void onGroupUpdated(const ::core_gen::RGroup & group, ::core_gen::ECallbackResult code) override;

    private:
        friend ::djinni::JniInterface<::core_gen::IGroupCallback, ::djinni_generated::NativeIGroupCallback>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/nextuc/IGroupCallback") };
    const jmethodID method_onGroupUpdated { ::djinni::jniGetMethodID(clazz.get(), "onGroupUpdated", "(Lcom/nextuc/RGroup;Lcom/nextuc/ECallbackResult;)V") };
};

}  // namespace djinni_generated
