// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include "djinni_support.hpp"
#include "i_contact_view_model.hpp"

namespace djinni_generated {

class NativeIContactViewModel final : ::djinni::JniInterface<::core_gen::IContactViewModel, NativeIContactViewModel> {
public:
    using CppType = std::shared_ptr<::core_gen::IContactViewModel>;
    using CppOptType = std::shared_ptr<::core_gen::IContactViewModel>;
    using JniType = jobject;

    using Boxed = NativeIContactViewModel;

    ~NativeIContactViewModel();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeIContactViewModel>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeIContactViewModel>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeIContactViewModel();
    friend ::djinni::JniClass<NativeIContactViewModel>;
    friend ::djinni::JniInterface<::core_gen::IContactViewModel, NativeIContactViewModel>;

};

}  // namespace djinni_generated
