// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include "djinni_support.hpp"
#include "i_group_update_ui_controller.hpp"

namespace djinni_generated {

class NativeIGroupUpdateUiController final : ::djinni::JniInterface<::core_gen::IGroupUpdateUiController, NativeIGroupUpdateUiController> {
public:
    using CppType = std::shared_ptr<::core_gen::IGroupUpdateUiController>;
    using CppOptType = std::shared_ptr<::core_gen::IGroupUpdateUiController>;
    using JniType = jobject;

    using Boxed = NativeIGroupUpdateUiController;

    ~NativeIGroupUpdateUiController();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeIGroupUpdateUiController>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeIGroupUpdateUiController>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeIGroupUpdateUiController();
    friend ::djinni::JniClass<NativeIGroupUpdateUiController>;
    friend ::djinni::JniInterface<::core_gen::IGroupUpdateUiController, NativeIGroupUpdateUiController>;

};

}  // namespace djinni_generated
