// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#pragma once

#include "djinni_support.hpp"
#include "i_group_table_data_source.hpp"

namespace djinni_generated {

class NativeIGroupTableDataSource final : ::djinni::JniInterface<::core_gen::IGroupTableDataSource, NativeIGroupTableDataSource> {
public:
    using CppType = std::shared_ptr<::core_gen::IGroupTableDataSource>;
    using CppOptType = std::shared_ptr<::core_gen::IGroupTableDataSource>;
    using JniType = jobject;

    using Boxed = NativeIGroupTableDataSource;

    ~NativeIGroupTableDataSource();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeIGroupTableDataSource>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeIGroupTableDataSource>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeIGroupTableDataSource();
    friend ::djinni::JniClass<NativeIGroupTableDataSource>;
    friend ::djinni::JniInterface<::core_gen::IGroupTableDataSource, NativeIGroupTableDataSource>;

};

}  // namespace djinni_generated
