// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

package com.nextuc;

public enum EAccountStatus {
    NOT_LOGGED_IN,
    IN_PROGRESS,
    LOGGED_IN,
    ;
}
