// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

package com.nextuc;

public enum EErrorType {
    SUCCESS,
    NETWORK_FAILURE,
    TIMEOUT,
    SERVER_FAILURE,
    PARSE_FAILURE,
    UNKNOWN,
    ;
}
