// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

package com.nextuc;

/** account */
public enum ELoginStatus {
    IN_PROGRESS,
    INVALID_CREDENTIALS,
    SUCCESS,
    FAILURE,
    ;
}
