// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_network_provider.djinni

package com.nextuc;

/** network provider */
public enum ERequestType {
    REST,
    DOWNLOAD,
    UPLOAD,
    ;
}
