// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_network_provider.djinni

package com.nextuc;

public enum ERequestResult {
    SUCCESS,
    NO_NETWORK,
    TIMEOUT,
    PARSE_ERROR,
    UNKNOW_ERROR,
    ;
}
