// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from event_loop.djinni

package com.nextuc;

public abstract class EventLoop {
    public abstract void post(AsyncTask task);
}
