// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

package com.nextuc;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class IContactViewModel {
    public abstract void setDataSource(IContactTableDataSource dataSource);

    public abstract IContactTableDataSource getDataSource();

    private static final class CppProxy extends IContactViewModel
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public void setDataSource(IContactTableDataSource dataSource)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_setDataSource(this.nativeRef, dataSource);
        }
        private native void native_setDataSource(long _nativeRef, IContactTableDataSource dataSource);

        @Override
        public IContactTableDataSource getDataSource()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getDataSource(this.nativeRef);
        }
        private native IContactTableDataSource native_getDataSource(long _nativeRef);
    }
}
