// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

package com.nextuc;

/**# data provider */
public abstract class IDataChangeDelegate {
    public abstract void onContactChanged(RContact contact);

    public abstract void onGroupChanged(RGroup group);
}
