// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_file_storage_provider.djinni

package com.nextuc;

/** log */
public abstract class IFileStorageProvider {
    public abstract String getDocumentsPath(String relativePath);

    public abstract void createRelativeFolder(String relativePath);

    public abstract void remove(String path);
}
