// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

package com.nextuc;

import java.util.ArrayList;
import java.util.concurrent.atomic.AtomicBoolean;

public abstract class IGroupCreateUiController {
    public abstract void createGroup(ArrayList<RContact> contacts, IGroupCallback callback);

    private static final class CppProxy extends IGroupCreateUiController
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public void createGroup(ArrayList<RContact> contacts, IGroupCallback callback)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_createGroup(this.nativeRef, contacts, callback);
        }
        private native void native_createGroup(long _nativeRef, ArrayList<RContact> contacts, IGroupCallback callback);
    }
}
