// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_logger.djinni

package com.nextuc;

public abstract class ILog {
    public abstract void error(String tag, String message);

    public abstract void warning(String tag, String message);

    public abstract void info(String tag, String message);

    public abstract void debug(String tag, String message);

    public abstract void verbose(String tag, String message);

    public abstract void setLogLevel(LogLevel level);

    public abstract boolean visible(LogLevel level);
}
