// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

package com.nextuc;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class ILoginUiController {
    public abstract void login();

    public abstract ILoginViewModel getViewModel();

    private static final class CppProxy extends ILoginUiController
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public void login()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_login(this.nativeRef);
        }
        private native void native_login(long _nativeRef);

        @Override
        public ILoginViewModel getViewModel()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getViewModel(this.nativeRef);
        }
        private native ILoginViewModel native_getViewModel(long _nativeRef);
    }
}
