// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_network_provider.djinni

package com.nextuc;

public abstract class INetworkStatusProvider {
    public abstract void setDelegate(INetworkStatusDelegate delegate);

    public abstract ENetworkStatus getNetworkStatus();

    public abstract void startMonitoring();

    public abstract void stopMonitoring();
}
