// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_network_provider.djinni

package com.nextuc;

public abstract class INetworkProvider {
    public abstract void request(RNetworkRequest request, INetworkCallback callback);
}
