// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

package com.nextuc;

/**#profile */
public abstract class IRequestUploadTokenCallback {
    public abstract void onTokenGet(RUploadToken token, RActionResult result);
}
