// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_task_dispatcher.djinni

package com.nextuc;

public abstract class ITaskDispatcher {
    public abstract void dispatchToUI(ITask task);

    public abstract void dispatchToCore(ITask task);

    public abstract void dispatchToDB(ITask task);

    public abstract void dispatchToBG(ITask task);
}
