// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

package com.nextuc;

import java.util.concurrent.atomic.AtomicBoolean;

/**# factory */
public abstract class IUiControllerFactory {
    /** login */
    public abstract ILifecycleUiController createLifecycleUiController(ILifecyleViewModelDelegate delegate);

    public abstract ILoginUiController createLoginUiController(IViewModelDelegate delegate);

    public abstract ISignupUiController createSignUpUiController(IViewModelDelegate delegate);

    /** contact */
    public abstract IContactUiController createContactUiController(IViewModelDelegate delegate);

    /** group */
    public abstract IGroupUiController createGroupUiController(IViewModelDelegate delegate);

    public abstract IGroupCreateUiController createGroupCreateUiController(IViewModelDelegate delegate);

    public abstract IGroupUpdateUiController createGroupUpdateUiController(IViewModelDelegate delegate);

    public abstract IGroupMemberUiController createGroupMemberUiController(IViewModelDelegate delegate);

    public abstract IGroupDetailUiController createGroupDetailUiController(IViewModelDelegate delegate);

    /** profiel */
    public abstract IProfileUiController createProfileUiController(IViewModelDelegate delegate);

    private static final class CppProxy extends IUiControllerFactory
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public ILifecycleUiController createLifecycleUiController(ILifecyleViewModelDelegate delegate)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_createLifecycleUiController(this.nativeRef, delegate);
        }
        private native ILifecycleUiController native_createLifecycleUiController(long _nativeRef, ILifecyleViewModelDelegate delegate);

        @Override
        public ILoginUiController createLoginUiController(IViewModelDelegate delegate)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_createLoginUiController(this.nativeRef, delegate);
        }
        private native ILoginUiController native_createLoginUiController(long _nativeRef, IViewModelDelegate delegate);

        @Override
        public ISignupUiController createSignUpUiController(IViewModelDelegate delegate)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_createSignUpUiController(this.nativeRef, delegate);
        }
        private native ISignupUiController native_createSignUpUiController(long _nativeRef, IViewModelDelegate delegate);

        @Override
        public IContactUiController createContactUiController(IViewModelDelegate delegate)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_createContactUiController(this.nativeRef, delegate);
        }
        private native IContactUiController native_createContactUiController(long _nativeRef, IViewModelDelegate delegate);

        @Override
        public IGroupUiController createGroupUiController(IViewModelDelegate delegate)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_createGroupUiController(this.nativeRef, delegate);
        }
        private native IGroupUiController native_createGroupUiController(long _nativeRef, IViewModelDelegate delegate);

        @Override
        public IGroupCreateUiController createGroupCreateUiController(IViewModelDelegate delegate)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_createGroupCreateUiController(this.nativeRef, delegate);
        }
        private native IGroupCreateUiController native_createGroupCreateUiController(long _nativeRef, IViewModelDelegate delegate);

        @Override
        public IGroupUpdateUiController createGroupUpdateUiController(IViewModelDelegate delegate)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_createGroupUpdateUiController(this.nativeRef, delegate);
        }
        private native IGroupUpdateUiController native_createGroupUpdateUiController(long _nativeRef, IViewModelDelegate delegate);

        @Override
        public IGroupMemberUiController createGroupMemberUiController(IViewModelDelegate delegate)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_createGroupMemberUiController(this.nativeRef, delegate);
        }
        private native IGroupMemberUiController native_createGroupMemberUiController(long _nativeRef, IViewModelDelegate delegate);

        @Override
        public IGroupDetailUiController createGroupDetailUiController(IViewModelDelegate delegate)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_createGroupDetailUiController(this.nativeRef, delegate);
        }
        private native IGroupDetailUiController native_createGroupDetailUiController(long _nativeRef, IViewModelDelegate delegate);

        @Override
        public IProfileUiController createProfileUiController(IViewModelDelegate delegate)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_createProfileUiController(this.nativeRef, delegate);
        }
        private native IProfileUiController native_createProfileUiController(long _nativeRef, IViewModelDelegate delegate);
    }
}
