// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

package com.nextuc;

public abstract class IViewModelDelegate {
    public abstract void onDataChanged();
}
