// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from core.djinni

package com.nextuc;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class IXplatformApplication {
    public abstract void initApp(IPalBundle palBundle);

    public abstract IUiControllerFactory getUiControllerFactory();

    public abstract IDataProvider getDataProvider();

    public static native IXplatformApplication sharedApplication();

    private static final class CppProxy extends IXplatformApplication
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public void initApp(IPalBundle palBundle)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_initApp(this.nativeRef, palBundle);
        }
        private native void native_initApp(long _nativeRef, IPalBundle palBundle);

        @Override
        public IUiControllerFactory getUiControllerFactory()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getUiControllerFactory(this.nativeRef);
        }
        private native IUiControllerFactory native_getUiControllerFactory(long _nativeRef);

        @Override
        public IDataProvider getDataProvider()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getDataProvider(this.nativeRef);
        }
        private native IDataProvider native_getDataProvider(long _nativeRef);
    }
}
