// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

package com.nextuc;

public final class ListChange {


    /*package*/ final int mFromIndex;

    /*package*/ final int mToIndex;

    public ListChange(
            int fromIndex,
            int toIndex) {
        this.mFromIndex = fromIndex;
        this.mToIndex = toIndex;
    }

    public int getFromIndex() {
        return mFromIndex;
    }

    public int getToIndex() {
        return mToIndex;
    }

    @Override
    public String toString() {
        return "ListChange{" +
                "mFromIndex=" + mFromIndex +
                "," + "mToIndex=" + mToIndex +
        "}";
    }

}
