// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_logger.djinni

package com.nextuc;

public enum LogLevel {
    VERBOSS,
    DEBUG,
    INFO,
    WARNING,
    ERROR,
    ;
}
