// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

package com.nextuc;

public final class RAccount {

    public static final String GRAND_TYPE_PASSWORD = "password";


    /*package*/ final String mUsername;

    /*package*/ final String mPassword;

    /*package*/ final String mGrantType;

    /*package*/ final String mId;

    /*package*/ final String mEmail;

    /*package*/ final String mFirstName;

    /*package*/ final String mLastName;

    /*package*/ final String mDisplayName;

    /*package*/ final String mCompanyId;

    /*package*/ final String mRongCloudToken;

    /*package*/ final String mAvatarUrl;

    public RAccount(
            String username,
            String password,
            String grantType,
            String id,
            String email,
            String firstName,
            String lastName,
            String displayName,
            String companyId,
            String rongCloudToken,
            String avatarUrl) {
        this.mUsername = username;
        this.mPassword = password;
        this.mGrantType = grantType;
        this.mId = id;
        this.mEmail = email;
        this.mFirstName = firstName;
        this.mLastName = lastName;
        this.mDisplayName = displayName;
        this.mCompanyId = companyId;
        this.mRongCloudToken = rongCloudToken;
        this.mAvatarUrl = avatarUrl;
    }

    public String getUsername() {
        return mUsername;
    }

    public String getPassword() {
        return mPassword;
    }

    public String getGrantType() {
        return mGrantType;
    }

    public String getId() {
        return mId;
    }

    public String getEmail() {
        return mEmail;
    }

    public String getFirstName() {
        return mFirstName;
    }

    public String getLastName() {
        return mLastName;
    }

    public String getDisplayName() {
        return mDisplayName;
    }

    public String getCompanyId() {
        return mCompanyId;
    }

    public String getRongCloudToken() {
        return mRongCloudToken;
    }

    public String getAvatarUrl() {
        return mAvatarUrl;
    }

    @Override
    public String toString() {
        return "RAccount{" +
                "mUsername=" + mUsername +
                "," + "mPassword=" + mPassword +
                "," + "mGrantType=" + mGrantType +
                "," + "mId=" + mId +
                "," + "mEmail=" + mEmail +
                "," + "mFirstName=" + mFirstName +
                "," + "mLastName=" + mLastName +
                "," + "mDisplayName=" + mDisplayName +
                "," + "mCompanyId=" + mCompanyId +
                "," + "mRongCloudToken=" + mRongCloudToken +
                "," + "mAvatarUrl=" + mAvatarUrl +
        "}";
    }

}
