// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

package com.nextuc;

/**
 * next uc
 *# common
 */
public final class RActionResult {


    /*package*/ final ECallbackResult mResult;

    /*package*/ final int mCode;

    public RActionResult(
            ECallbackResult result,
            int code) {
        this.mResult = result;
        this.mCode = code;
    }

    public ECallbackResult getResult() {
        return mResult;
    }

    public int getCode() {
        return mCode;
    }

    @Override
    public String toString() {
        return "RActionResult{" +
                "mResult=" + mResult +
                "," + "mCode=" + mCode +
        "}";
    }

}
