// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

package com.nextuc;

public final class RAvatarDomain {


    /*package*/ final String mDomain;

    public RAvatarDomain(
            String domain) {
        this.mDomain = domain;
    }

    public String getDomain() {
        return mDomain;
    }

    @Override
    public String toString() {
        return "RAvatarDomain{" +
                "mDomain=" + mDomain +
        "}";
    }

}
