// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

package com.nextuc;

public final class RAvatarInfo {


    /*package*/ final String mUserId;

    /*package*/ final String mAvatarUrl;

    /*package*/ final String mAvatarUploadToken;

    public RAvatarInfo(
            String userId,
            String avatarUrl,
            String avatarUploadToken) {
        this.mUserId = userId;
        this.mAvatarUrl = avatarUrl;
        this.mAvatarUploadToken = avatarUploadToken;
    }

    public String getUserId() {
        return mUserId;
    }

    public String getAvatarUrl() {
        return mAvatarUrl;
    }

    public String getAvatarUploadToken() {
        return mAvatarUploadToken;
    }

    @Override
    public String toString() {
        return "RAvatarInfo{" +
                "mUserId=" + mUserId +
                "," + "mAvatarUrl=" + mAvatarUrl +
                "," + "mAvatarUploadToken=" + mAvatarUploadToken +
        "}";
    }

}
