// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

package com.nextuc;

import java.util.ArrayList;

public final class RContactResponse {


    /*package*/ final ArrayList<RContact> mContacts;

    public RContactResponse(
            ArrayList<RContact> contacts) {
        this.mContacts = contacts;
    }

    public ArrayList<RContact> getContacts() {
        return mContacts;
    }

    @Override
    public String toString() {
        return "RContactResponse{" +
                "mContacts=" + mContacts +
        "}";
    }

}
