// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

package com.nextuc;

/** contact  */
public final class RContact {


    /*package*/ final String mUsername;

    /*package*/ final String mId;

    /*package*/ final String mEmail;

    /*package*/ final String mFirstName;

    /*package*/ final String mLastName;

    /*package*/ final String mDisplayName;

    /*package*/ final String mCompanyId;

    /*package*/ final String mAvatarUrl;

    public RContact(
            String username,
            String id,
            String email,
            String firstName,
            String lastName,
            String displayName,
            String companyId,
            String avatarUrl) {
        this.mUsername = username;
        this.mId = id;
        this.mEmail = email;
        this.mFirstName = firstName;
        this.mLastName = lastName;
        this.mDisplayName = displayName;
        this.mCompanyId = companyId;
        this.mAvatarUrl = avatarUrl;
    }

    public String getUsername() {
        return mUsername;
    }

    public String getId() {
        return mId;
    }

    public String getEmail() {
        return mEmail;
    }

    public String getFirstName() {
        return mFirstName;
    }

    public String getLastName() {
        return mLastName;
    }

    public String getDisplayName() {
        return mDisplayName;
    }

    public String getCompanyId() {
        return mCompanyId;
    }

    public String getAvatarUrl() {
        return mAvatarUrl;
    }

    @Override
    public String toString() {
        return "RContact{" +
                "mUsername=" + mUsername +
                "," + "mId=" + mId +
                "," + "mEmail=" + mEmail +
                "," + "mFirstName=" + mFirstName +
                "," + "mLastName=" + mLastName +
                "," + "mDisplayName=" + mDisplayName +
                "," + "mCompanyId=" + mCompanyId +
                "," + "mAvatarUrl=" + mAvatarUrl +
        "}";
    }

}
