// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

package com.nextuc;

public final class RFutureError {


    /*package*/ final EErrorType mType;

    /*package*/ final RServerError mServerSrror;

    /*package*/ final RParsingError mParsingError;

    /*package*/ final RNetworkError mNetworkError;

    /*package*/ final String mGeneralMessage;

    public RFutureError(
            EErrorType type,
            RServerError serverSrror,
            RParsingError parsingError,
            RNetworkError networkError,
            String generalMessage) {
        this.mType = type;
        this.mServerSrror = serverSrror;
        this.mParsingError = parsingError;
        this.mNetworkError = networkError;
        this.mGeneralMessage = generalMessage;
    }

    public EErrorType getType() {
        return mType;
    }

    public RServerError getServerSrror() {
        return mServerSrror;
    }

    public RParsingError getParsingError() {
        return mParsingError;
    }

    public RNetworkError getNetworkError() {
        return mNetworkError;
    }

    public String getGeneralMessage() {
        return mGeneralMessage;
    }

    @Override
    public String toString() {
        return "RFutureError{" +
                "mType=" + mType +
                "," + "mServerSrror=" + mServerSrror +
                "," + "mParsingError=" + mParsingError +
                "," + "mNetworkError=" + mNetworkError +
                "," + "mGeneralMessage=" + mGeneralMessage +
        "}";
    }

}
