// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

package com.nextuc;

public final class RGroupUpdateResponse {


    /*package*/ final RGroup mGroup;

    public RGroupUpdateResponse(
            RGroup group) {
        this.mGroup = group;
    }

    public RGroup getGroup() {
        return mGroup;
    }

    @Override
    public String toString() {
        return "RGroupUpdateResponse{" +
                "mGroup=" + mGroup +
        "}";
    }

}
