// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

package com.nextuc;

import java.util.ArrayList;

public final class RGroupResponse {


    /*package*/ final ArrayList<RGroup> mGroups;

    public RGroupResponse(
            ArrayList<RGroup> groups) {
        this.mGroups = groups;
    }

    public ArrayList<RGroup> getGroups() {
        return mGroups;
    }

    @Override
    public String toString() {
        return "RGroupResponse{" +
                "mGroups=" + mGroups +
        "}";
    }

}
