// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

package com.nextuc;

public final class RIntegerIdError {


    /*package*/ final long mId;

    /*package*/ final RFutureError mError;

    public RIntegerIdError(
            long id,
            RFutureError error) {
        this.mId = id;
        this.mError = error;
    }

    public long getId() {
        return mId;
    }

    public RFutureError getError() {
        return mError;
    }

    @Override
    public String toString() {
        return "RIntegerIdError{" +
                "mId=" + mId +
                "," + "mError=" + mError +
        "}";
    }

}
