// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_network_provider.djinni

package com.nextuc;

import java.util.ArrayList;
import java.util.HashMap;

public final class RNetworkResponse {


    /*package*/ final long mCode;

    /*package*/ final HashMap<String, ArrayList<String>> mHeader;

    /*package*/ final ERequestResult mStatus;

    /*package*/ final byte[] mData;

    /*package*/ final String mContentType;

    public RNetworkResponse(
            long code,
            HashMap<String, ArrayList<String>> header,
            ERequestResult status,
            byte[] data,
            String contentType) {
        this.mCode = code;
        this.mHeader = header;
        this.mStatus = status;
        this.mData = data;
        this.mContentType = contentType;
    }

    public long getCode() {
        return mCode;
    }

    public HashMap<String, ArrayList<String>> getHeader() {
        return mHeader;
    }

    public ERequestResult getStatus() {
        return mStatus;
    }

    public byte[] getData() {
        return mData;
    }

    public String getContentType() {
        return mContentType;
    }

    @Override
    public String toString() {
        return "RNetworkResponse{" +
                "mCode=" + mCode +
                "," + "mHeader=" + mHeader +
                "," + "mStatus=" + mStatus +
                "," + "mData=" + mData +
                "," + "mContentType=" + mContentType +
        "}";
    }

}
