// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

package com.nextuc;

public final class RNetworkError {


    /*package*/ final int mErrorCode;

    public RNetworkError(
            int errorCode) {
        this.mErrorCode = errorCode;
    }

    public int getErrorCode() {
        return mErrorCode;
    }

    @Override
    public String toString() {
        return "RNetworkError{" +
                "mErrorCode=" + mErrorCode +
        "}";
    }

}
