// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

package com.nextuc;

public final class RParsingError {


    /*package*/ final String mMessage;

    public RParsingError(
            String message) {
        this.mMessage = message;
    }

    public String getMessage() {
        return mMessage;
    }

    @Override
    public String toString() {
        return "RParsingError{" +
                "mMessage=" + mMessage +
        "}";
    }

}
