// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

package com.nextuc;

public final class RServerErrorDetail {


    /*package*/ final String mErrorCode;

    /*package*/ final String mMessage;

    /*package*/ final String mParameter;

    /*package*/ final String mParameterName;

    public RServerErrorDetail(
            String errorCode,
            String message,
            String parameter,
            String parameterName) {
        this.mErrorCode = errorCode;
        this.mMessage = message;
        this.mParameter = parameter;
        this.mParameterName = parameterName;
    }

    public String getErrorCode() {
        return mErrorCode;
    }

    public String getMessage() {
        return mMessage;
    }

    public String getParameter() {
        return mParameter;
    }

    public String getParameterName() {
        return mParameterName;
    }

    @Override
    public String toString() {
        return "RServerErrorDetail{" +
                "mErrorCode=" + mErrorCode +
                "," + "mMessage=" + mMessage +
                "," + "mParameter=" + mParameter +
                "," + "mParameterName=" + mParameterName +
        "}";
    }

}
