// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

package com.nextuc;

public final class RUploadToken {


    /*package*/ final String mUserId;

    /*package*/ final String mAvatarUploadToken;

    public RUploadToken(
            String userId,
            String avatarUploadToken) {
        this.mUserId = userId;
        this.mAvatarUploadToken = avatarUploadToken;
    }

    public String getUserId() {
        return mUserId;
    }

    public String getAvatarUploadToken() {
        return mAvatarUploadToken;
    }

    @Override
    public String toString() {
        return "RUploadToken{" +
                "mUserId=" + mUserId +
                "," + "mAvatarUploadToken=" + mAvatarUploadToken +
        "}";
    }

}
