// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from thread.djinni

package com.nextuc;

public abstract class ThreadLauncher {
    /** name is nullable */
    public abstract void startThread(String name, AsyncTask runFn);
}
