// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

package com.nextuc;

import java.util.ArrayList;

public abstract class UserListVmObserver {
    public abstract void onUpdate(ArrayList<ListChange> changes, UserListVm newData);
}
