// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_network_provider.djinni

#import <Foundation/Foundation.h>

/** network provider */
typedef NS_ENUM(NSInteger, CoreERequestType)
{
    CoreERequestTypeRest,
    CoreERequestTypeDownload,
    CoreERequestTypeUpload,
};
