// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#import "CoreRServerError.h"


@implementation CoreRServerError

- (nonnull instancetype)initWithErrorCode:(nullable NSString *)errorCode
                                  message:(nullable NSString *)message
                            parameterName:(nullable NSString *)parameterName
                                parameter:(nullable NSString *)parameter
                                   errors:(nonnull NSArray<CoreRServerErrorDetail *> *)errors
                                    error:(nullable NSString *)error
                         errorDescription:(nullable NSString *)errorDescription
{
    if (self = [super init]) {
        _errorCode = [errorCode copy];
        _message = [message copy];
        _parameterName = [parameterName copy];
        _parameter = [parameter copy];
        _errors = [errors copy];
        _error = [error copy];
        _errorDescription = [errorDescription copy];
    }
    return self;
}

+ (nonnull instancetype)rServerErrorWithErrorCode:(nullable NSString *)errorCode
                                          message:(nullable NSString *)message
                                    parameterName:(nullable NSString *)parameterName
                                        parameter:(nullable NSString *)parameter
                                           errors:(nonnull NSArray<CoreRServerErrorDetail *> *)errors
                                            error:(nullable NSString *)error
                                 errorDescription:(nullable NSString *)errorDescription
{
    return [[self alloc] initWithErrorCode:errorCode
                                   message:message
                             parameterName:parameterName
                                 parameter:parameter
                                    errors:errors
                                     error:error
                          errorDescription:errorDescription];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p errorCode:%@ message:%@ parameterName:%@ parameter:%@ errors:%@ error:%@ errorDescription:%@>", self.class, self, self.errorCode, self.message, self.parameterName, self.parameter, self.errors, self.error, self.errorDescription];
}

@end
