// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#import "CoreRUploadToken+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto RUploadToken::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.userId),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.avatarUploadToken)};
}

auto RUploadToken::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[CoreRUploadToken alloc] initWithUserId:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.userId))
                                  avatarUploadToken:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.avatarUploadToken))];
}

}  // namespace djinni_generated
