// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#import "CoreRServerError+Private.h"
#import "CoreRServerErrorDetail+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto RServerError::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.errorCode),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.message),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.parameterName),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.parameter),
            ::djinni::List<::djinni_generated::RServerErrorDetail>::toCpp(obj.errors),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.error),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.errorDescription)};
}

auto RServerError::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[CoreRServerError alloc] initWithErrorCode:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.error_code))
                                               message:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.message))
                                         parameterName:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.parameterName))
                                             parameter:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.parameter))
                                                errors:(::djinni::List<::djinni_generated::RServerErrorDetail>::fromCpp(cpp.errors))
                                                 error:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.error))
                                      errorDescription:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.errorDescription))];
}

}  // namespace djinni_generated
