// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_network_provider.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, CoreENetworkMethod)
{
    CoreENetworkMethodGet,
    CoreENetworkMethodPost,
    CoreENetworkMethodDelete,
    CoreENetworkMethodPut,
};
