// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#import "CoreRAccountResponse.h"


@implementation CoreRAccountResponse

- (nonnull instancetype)initWithAccessToken:(nonnull NSString *)accessToken
                               refreshToken:(nonnull NSString *)refreshToken
                                  expiresIn:(nullable NSNumber *)expiresIn
                                       user:(nonnull CoreRAccount *)user
{
    if (self = [super init]) {
        _accessToken = [accessToken copy];
        _refreshToken = [refreshToken copy];
        _expiresIn = expiresIn;
        _user = user;
    }
    return self;
}

+ (nonnull instancetype)rAccountResponseWithAccessToken:(nonnull NSString *)accessToken
                                           refreshToken:(nonnull NSString *)refreshToken
                                              expiresIn:(nullable NSNumber *)expiresIn
                                                   user:(nonnull CoreRAccount *)user
{
    return [[self alloc] initWithAccessToken:accessToken
                                refreshToken:refreshToken
                                   expiresIn:expiresIn
                                        user:user];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p accessToken:%@ refreshToken:%@ expiresIn:%@ user:%@>", self.class, self, self.accessToken, self.refreshToken, self.expiresIn, self.user];
}

@end
