// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#import "CoreIGroupUiController+Private.h"
#import "CoreIGroupUiController.h"
#import "CoreIGroupViewModel+Private.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#include <exception>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface CoreIGroupUiController ()

- (id)initWithCpp:(const std::shared_ptr<::core_gen::IGroupUiController>&)cppRef;

@end

@implementation CoreIGroupUiController {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::core_gen::IGroupUiController>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::core_gen::IGroupUiController>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (nullable CoreIGroupViewModel *)getViewModel {
    try {
        auto r = _cppRefHandle.get()->getViewModel();
        return ::djinni_generated::IGroupViewModel::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto IGroupUiController::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto IGroupUiController::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<CoreIGroupUiController>(cpp);
}

}  // namespace djinni_generated

@end
