// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_task_dispatcher.djinni

#import "CoreITask+Private.h"
#import "CoreITask.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface CoreITask ()

- (id)initWithCpp:(const std::shared_ptr<::core_gen::ITask>&)cppRef;

@end

@implementation CoreITask {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::core_gen::ITask>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::core_gen::ITask>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (int32_t)getId {
    try {
        auto r = _cppRefHandle.get()->getId();
        return ::djinni::I32::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)execute {
    try {
        _cppRefHandle.get()->execute();
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto ITask::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto ITask::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<CoreITask>(cpp);
}

}  // namespace djinni_generated

@end
