// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#include "user_list_vm_handle.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class CoreUserListVmHandle;

namespace djinni_generated {

class UserListVmHandle
{
public:
    using CppType = std::shared_ptr<::core_gen::UserListVmHandle>;
    using CppOptType = std::shared_ptr<::core_gen::UserListVmHandle>;
    using ObjcType = CoreUserListVmHandle*;

    using Boxed = UserListVmHandle;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

