// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#import "CoreRUploadToken.h"


@implementation CoreRUploadToken

- (nonnull instancetype)initWithUserId:(nullable NSString *)userId
                     avatarUploadToken:(nullable NSString *)avatarUploadToken
{
    if (self = [super init]) {
        _userId = [userId copy];
        _avatarUploadToken = [avatarUploadToken copy];
    }
    return self;
}

+ (nonnull instancetype)rUploadTokenWithUserId:(nullable NSString *)userId
                             avatarUploadToken:(nullable NSString *)avatarUploadToken
{
    return [[self alloc] initWithUserId:userId
                      avatarUploadToken:avatarUploadToken];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p userId:%@ avatarUploadToken:%@>", self.class, self, self.userId, self.avatarUploadToken];
}

@end
