// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from core.djinni

#import <Foundation/Foundation.h>
@class CoreApi;
@class CoreUserListVmHandle;
@protocol CoreEventLoop;
@protocol CoreHttp;
@protocol CoreThreadLauncher;


@interface CoreApi : NSObject

+ (nullable CoreApi *)createApi:(nonnull NSString *)rootPath
                       uiThread:(nullable id<CoreEventLoop>)uiThread
                       httpImpl:(nullable id<CoreHttp>)httpImpl
                       launcher:(nullable id<CoreThreadLauncher>)launcher;

- (nullable CoreUserListVmHandle *)observerUserList;

- (BOOL)hasUser;

- (nonnull NSString *)getUsername;

- (void)setUsername:(nonnull NSString *)username;

@end
