// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#import <Foundation/Foundation.h>
@class CoreIGroupViewModel;


@interface CoreIGroupUiController : NSObject

- (nullable CoreIGroupViewModel *)getViewModel;

@end
