// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#import "CoreRAvatarInfo.h"
#include "r_avatar_info.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class CoreRAvatarInfo;

namespace djinni_generated {

struct RAvatarInfo
{
    using CppType = ::core_gen::RAvatarInfo;
    using ObjcType = CoreRAvatarInfo*;

    using Boxed = RAvatarInfo;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
