// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#include "i_lifecyle_view_model_delegate.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol CoreILifecyleViewModelDelegate;

namespace djinni_generated {

class ILifecyleViewModelDelegate
{
public:
    using CppType = std::shared_ptr<::core_gen::ILifecyleViewModelDelegate>;
    using CppOptType = std::shared_ptr<::core_gen::ILifecyleViewModelDelegate>;
    using ObjcType = id<CoreILifecyleViewModelDelegate>;

    using Boxed = ILifecyleViewModelDelegate;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

