// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#import "CoreIUiControllerFactory+Private.h"
#import "CoreIUiControllerFactory.h"
#import "CoreIContactUiController+Private.h"
#import "CoreIGroupCreateUiController+Private.h"
#import "CoreIGroupDetailUiController+Private.h"
#import "CoreIGroupMemberUiController+Private.h"
#import "CoreIGroupUiController+Private.h"
#import "CoreIGroupUpdateUiController+Private.h"
#import "CoreILifecycleUiController+Private.h"
#import "CoreILifecyleViewModelDelegate+Private.h"
#import "CoreILoginUiController+Private.h"
#import "CoreIProfileUiController+Private.h"
#import "CoreISignupUiController+Private.h"
#import "CoreIViewModelDelegate+Private.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#include <exception>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface CoreIUiControllerFactory ()

- (id)initWithCpp:(const std::shared_ptr<::core_gen::IUiControllerFactory>&)cppRef;

@end

@implementation CoreIUiControllerFactory {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::core_gen::IUiControllerFactory>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::core_gen::IUiControllerFactory>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (nullable CoreILifecycleUiController *)createLifecycleUiController:(nullable id<CoreILifecyleViewModelDelegate>)delegate {
    try {
        auto r = _cppRefHandle.get()->createLifecycleUiController(::djinni_generated::ILifecyleViewModelDelegate::toCpp(delegate));
        return ::djinni_generated::ILifecycleUiController::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nullable CoreILoginUiController *)createLoginUiController:(nullable id<CoreIViewModelDelegate>)delegate {
    try {
        auto r = _cppRefHandle.get()->createLoginUiController(::djinni_generated::IViewModelDelegate::toCpp(delegate));
        return ::djinni_generated::ILoginUiController::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nullable CoreISignupUiController *)createSignUpUiController:(nullable id<CoreIViewModelDelegate>)delegate {
    try {
        auto r = _cppRefHandle.get()->createSignUpUiController(::djinni_generated::IViewModelDelegate::toCpp(delegate));
        return ::djinni_generated::ISignupUiController::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nullable CoreIContactUiController *)createContactUiController:(nullable id<CoreIViewModelDelegate>)delegate {
    try {
        auto r = _cppRefHandle.get()->createContactUiController(::djinni_generated::IViewModelDelegate::toCpp(delegate));
        return ::djinni_generated::IContactUiController::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nullable CoreIGroupUiController *)createGroupUiController:(nullable id<CoreIViewModelDelegate>)delegate {
    try {
        auto r = _cppRefHandle.get()->createGroupUiController(::djinni_generated::IViewModelDelegate::toCpp(delegate));
        return ::djinni_generated::IGroupUiController::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nullable CoreIGroupCreateUiController *)createGroupCreateUiController:(nullable id<CoreIViewModelDelegate>)delegate {
    try {
        auto r = _cppRefHandle.get()->createGroupCreateUiController(::djinni_generated::IViewModelDelegate::toCpp(delegate));
        return ::djinni_generated::IGroupCreateUiController::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nullable CoreIGroupUpdateUiController *)createGroupUpdateUiController:(nullable id<CoreIViewModelDelegate>)delegate {
    try {
        auto r = _cppRefHandle.get()->createGroupUpdateUiController(::djinni_generated::IViewModelDelegate::toCpp(delegate));
        return ::djinni_generated::IGroupUpdateUiController::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nullable CoreIGroupMemberUiController *)createGroupMemberUiController:(nullable id<CoreIViewModelDelegate>)delegate {
    try {
        auto r = _cppRefHandle.get()->createGroupMemberUiController(::djinni_generated::IViewModelDelegate::toCpp(delegate));
        return ::djinni_generated::IGroupMemberUiController::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nullable CoreIGroupDetailUiController *)createGroupDetailUiController:(nullable id<CoreIViewModelDelegate>)delegate {
    try {
        auto r = _cppRefHandle.get()->createGroupDetailUiController(::djinni_generated::IViewModelDelegate::toCpp(delegate));
        return ::djinni_generated::IGroupDetailUiController::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nullable CoreIProfileUiController *)createProfileUiController:(nullable id<CoreIViewModelDelegate>)delegate {
    try {
        auto r = _cppRefHandle.get()->createProfileUiController(::djinni_generated::IViewModelDelegate::toCpp(delegate));
        return ::djinni_generated::IProfileUiController::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto IUiControllerFactory::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto IUiControllerFactory::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<CoreIUiControllerFactory>(cpp);
}

}  // namespace djinni_generated

@end
