// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#import <Foundation/Foundation.h>

@interface CoreRAvatarDomain : NSObject
- (nonnull instancetype)initWithDomain:(nullable NSString *)domain;
+ (nonnull instancetype)rAvatarDomainWithDomain:(nullable NSString *)domain;

@property (nonatomic, readonly, nullable) NSString * domain;

@end
