// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#include "i_group_update_ui_controller.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class CoreIGroupUpdateUiController;

namespace djinni_generated {

class IGroupUpdateUiController
{
public:
    using CppType = std::shared_ptr<::core_gen::IGroupUpdateUiController>;
    using CppOptType = std::shared_ptr<::core_gen::IGroupUpdateUiController>;
    using ObjcType = CoreIGroupUpdateUiController*;

    using Boxed = IGroupUpdateUiController;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

