// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#import "CoreRGroup.h"
#import <Foundation/Foundation.h>

@interface CoreRGroupUpdateResponse : NSObject
- (nonnull instancetype)initWithGroup:(nullable CoreRGroup *)group;
+ (nonnull instancetype)rGroupUpdateResponseWithGroup:(nullable CoreRGroup *)group;

@property (nonatomic, readonly, nullable) CoreRGroup * group;

@end
