// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#import "CoreListChange.h"
#include "list_change.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class CoreListChange;

namespace djinni_generated {

struct ListChange
{
    using CppType = ::core_gen::ListChange;
    using ObjcType = CoreListChange*;

    using Boxed = ListChange;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
