// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#import <Foundation/Foundation.h>
@class CoreILoginViewModel;


@interface CoreILoginUiController : NSObject

- (void)login;

- (nullable CoreILoginViewModel *)getViewModel;

@end
