// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#import "CoreRParsingError.h"


@implementation CoreRParsingError

- (nonnull instancetype)initWithMessage:(nonnull NSString *)message
{
    if (self = [super init]) {
        _message = [message copy];
    }
    return self;
}

+ (nonnull instancetype)rParsingErrorWithMessage:(nonnull NSString *)message
{
    return [[self alloc] initWithMessage:message];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p message:%@>", self.class, self, self.message];
}

@end
