// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#import "CoreRContact+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto RContact::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.username),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.id),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.email),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.firstName),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.lastName),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.displayName),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.companyId),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.avatarUrl)};
}

auto RContact::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[CoreRContact alloc] initWithUsername:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.username))
                                               id:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.id))
                                            email:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.email))
                                        firstName:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.firstName))
                                         lastName:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.lastName))
                                      displayName:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.displayName))
                                        companyId:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.companyId))
                                        avatarUrl:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.avatarUrl))];
}

}  // namespace djinni_generated
