// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#import "CoreIViewModelDelegate+Private.h"
#import "CoreIViewModelDelegate.h"
#import "DJIObjcWrapperCache+Private.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class IViewModelDelegate::ObjcProxy final
: public ::core_gen::IViewModelDelegate
, public ::djinni::ObjcProxyCache::Handle<ObjcType>
{
public:
    using Handle::Handle;
    void onDataChanged() override
    {
        @autoreleasepool {
            [Handle::get() onDataChanged];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto IViewModelDelegate::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto IViewModelDelegate::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).Handle::get();
}

}  // namespace djinni_generated
