// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#import <Foundation/Foundation.h>


@interface CoreHttpCallback : NSObject

- (void)onNetworkError;

- (void)onSuccess:(int16_t)httpCode
             data:(nonnull NSString *)data;

@end
