// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#import "CoreUserListVmCell.h"
#include "user_list_vm_cell.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class CoreUserListVmCell;

namespace djinni_generated {

struct UserListVmCell
{
    using CppType = ::core_gen::UserListVmCell;
    using ObjcType = CoreUserListVmCell*;

    using Boxed = UserListVmCell;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
