// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_task_dispatcher.djinni

#include "i_task_dispatcher.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol CoreITaskDispatcher;

namespace djinni_generated {

class ITaskDispatcher
{
public:
    using CppType = std::shared_ptr<::core_gen::ITaskDispatcher>;
    using CppOptType = std::shared_ptr<::core_gen::ITaskDispatcher>;
    using ObjcType = id<CoreITaskDispatcher>;

    using Boxed = ITaskDispatcher;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

