// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#import "CoreRGroup.h"
#import <Foundation/Foundation.h>

@interface CoreRGroupResponse : NSObject
- (nonnull instancetype)initWithGroups:(nullable NSArray<CoreRGroup *> *)groups;
+ (nonnull instancetype)rGroupResponseWithGroups:(nullable NSArray<CoreRGroup *> *)groups;

@property (nonatomic, readonly, nullable) NSArray<CoreRGroup *> * groups;

@end
