// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_network_provider.djinni

#import "CoreRNetworkResponse.h"
#include "r_network_response.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class CoreRNetworkResponse;

namespace djinni_generated {

struct RNetworkResponse
{
    using CppType = ::core_gen::RNetworkResponse;
    using ObjcType = CoreRNetworkResponse*;

    using Boxed = RNetworkResponse;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
