// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#include "i_group_callback.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol CoreIGroupCallback;

namespace djinni_generated {

class IGroupCallback
{
public:
    using CppType = std::shared_ptr<::core_gen::IGroupCallback>;
    using CppOptType = std::shared_ptr<::core_gen::IGroupCallback>;
    using ObjcType = id<CoreIGroupCallback>;

    using Boxed = IGroupCallback;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

