// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_logger.djinni

#import "CoreLogLevel.h"
#import <Foundation/Foundation.h>


@protocol CoreILog

- (void)error:(nonnull NSString *)tag
      message:(nonnull NSString *)message;

- (void)warning:(nonnull NSString *)tag
        message:(nonnull NSString *)message;

- (void)info:(nonnull NSString *)tag
     message:(nonnull NSString *)message;

- (void)debug:(nonnull NSString *)tag
      message:(nonnull NSString *)message;

- (void)verbose:(nonnull NSString *)tag
        message:(nonnull NSString *)message;

- (void)setLogLevel:(CoreLogLevel)level;

- (BOOL)visible:(CoreLogLevel)level;

@end
