// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#import "CoreRAccount.h"
#include "r_account.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class CoreRAccount;

namespace djinni_generated {

struct RAccount
{
    using CppType = ::core_gen::RAccount;
    using ObjcType = CoreRAccount*;

    using Boxed = RAccount;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
