// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from core.djinni

#include "i_xplatform_application.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class CoreIXplatformApplication;

namespace djinni_generated {

class IXplatformApplication
{
public:
    using CppType = std::shared_ptr<::core_gen::IXplatformApplication>;
    using CppOptType = std::shared_ptr<::core_gen::IXplatformApplication>;
    using ObjcType = CoreIXplatformApplication*;

    using Boxed = IXplatformApplication;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

