// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#include "i_request_upload_token_callback.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol CoreIRequestUploadTokenCallback;

namespace djinni_generated {

class IRequestUploadTokenCallback
{
public:
    using CppType = std::shared_ptr<::core_gen::IRequestUploadTokenCallback>;
    using CppOptType = std::shared_ptr<::core_gen::IRequestUploadTokenCallback>;
    using ObjcType = id<CoreIRequestUploadTokenCallback>;

    using Boxed = IRequestUploadTokenCallback;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

