// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#import "CoreRActionResult+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto RActionResult::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::Enum<::core_gen::ECallbackResult, CoreECallbackResult>::toCpp(obj.result),
            ::djinni::I32::toCpp(obj.code)};
}

auto RActionResult::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[CoreRActionResult alloc] initWithResult:(::djinni::Enum<::core_gen::ECallbackResult, CoreECallbackResult>::fromCpp(cpp.result))
                                                code:(::djinni::I32::fromCpp(cpp.code))];
}

}  // namespace djinni_generated
