// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#import "CoreIGroupDetailViewModel+Private.h"
#import "CoreIGroupDetailViewModel.h"
#import "CoreRGroup+Private.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#include <exception>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface CoreIGroupDetailViewModel ()

- (id)initWithCpp:(const std::shared_ptr<::core_gen::IGroupDetailViewModel>&)cppRef;

@end

@implementation CoreIGroupDetailViewModel {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::core_gen::IGroupDetailViewModel>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::core_gen::IGroupDetailViewModel>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (void)setGroup:(nonnull CoreRGroup *)group {
    try {
        _cppRefHandle.get()->setGroup(::djinni_generated::RGroup::toCpp(group));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull CoreRGroup *)getGroup {
    try {
        auto r = _cppRefHandle.get()->getGroup();
        return ::djinni_generated::RGroup::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto IGroupDetailViewModel::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto IGroupDetailViewModel::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<CoreIGroupDetailViewModel>(cpp);
}

}  // namespace djinni_generated

@end
