// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#import <Foundation/Foundation.h>

/** contact  */
@interface CoreRContact : NSObject
- (nonnull instancetype)initWithUsername:(nullable NSString *)username
                                      id:(nullable NSString *)id
                                   email:(nullable NSString *)email
                               firstName:(nullable NSString *)firstName
                                lastName:(nullable NSString *)lastName
                             displayName:(nullable NSString *)displayName
                               companyId:(nullable NSString *)companyId
                               avatarUrl:(nullable NSString *)avatarUrl;
+ (nonnull instancetype)rContactWithUsername:(nullable NSString *)username
                                          id:(nullable NSString *)id
                                       email:(nullable NSString *)email
                                   firstName:(nullable NSString *)firstName
                                    lastName:(nullable NSString *)lastName
                                 displayName:(nullable NSString *)displayName
                                   companyId:(nullable NSString *)companyId
                                   avatarUrl:(nullable NSString *)avatarUrl;

@property (nonatomic, readonly, nullable) NSString * username;

@property (nonatomic, readonly, nullable) NSString * id;

@property (nonatomic, readonly, nullable) NSString * email;

@property (nonatomic, readonly, nullable) NSString * firstName;

@property (nonatomic, readonly, nullable) NSString * lastName;

@property (nonatomic, readonly, nullable) NSString * displayName;

@property (nonatomic, readonly, nullable) NSString * companyId;

@property (nonatomic, readonly, nullable) NSString * avatarUrl;

@end
