// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#include "i_signup_ui_controller.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class CoreISignupUiController;

namespace djinni_generated {

class ISignupUiController
{
public:
    using CppType = std::shared_ptr<::core_gen::ISignupUiController>;
    using CppOptType = std::shared_ptr<::core_gen::ISignupUiController>;
    using ObjcType = CoreISignupUiController*;

    using Boxed = ISignupUiController;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

