// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#import "CoreRContact.h"
#include "r_contact.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class CoreRContact;

namespace djinni_generated {

struct RContact
{
    using CppType = ::core_gen::RContact;
    using ObjcType = CoreRContact*;

    using Boxed = RContact;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
