// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from event_loop.djinni

#import "CoreAsyncTask+Private.h"
#import "CoreAsyncTask.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#include <exception>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface CoreAsyncTask ()

- (id)initWithCpp:(const std::shared_ptr<::core_gen::AsyncTask>&)cppRef;

@end

@implementation CoreAsyncTask {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::core_gen::AsyncTask>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::core_gen::AsyncTask>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (void)execute {
    try {
        _cppRefHandle.get()->execute();
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto AsyncTask::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto AsyncTask::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<CoreAsyncTask>(cpp);
}

}  // namespace djinni_generated

@end
