// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_network_provider.djinni

#import "CoreRNetworkResponse.h"


@implementation CoreRNetworkResponse

- (nonnull instancetype)initWithCode:(int64_t)code
                              header:(nonnull NSDictionary<NSString *, NSArray<NSString *> *> *)header
                              status:(CoreERequestResult)status
                                data:(nonnull NSData *)data
                         contentType:(nonnull NSString *)contentType
{
    if (self = [super init]) {
        _code = code;
        _header = [header copy];
        _status = status;
        _data = [data copy];
        _contentType = [contentType copy];
    }
    return self;
}

+ (nonnull instancetype)rNetworkResponseWithCode:(int64_t)code
                                          header:(nonnull NSDictionary<NSString *, NSArray<NSString *> *> *)header
                                          status:(CoreERequestResult)status
                                            data:(nonnull NSData *)data
                                     contentType:(nonnull NSString *)contentType
{
    return [[self alloc] initWithCode:code
                               header:header
                               status:status
                                 data:data
                          contentType:contentType];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p code:%@ header:%@ status:%@ data:%@ contentType:%@>", self.class, self, @(self.code), self.header, @(self.status), self.data, self.contentType];
}

@end
