// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_network_provider.djinni

#import "CoreENetworkStatus.h"
#import <Foundation/Foundation.h>
@class CoreINetworkStatusDelegate;


@protocol CoreINetworkStatusProvider

- (void)setDelegate:(nullable CoreINetworkStatusDelegate *)delegate;

- (CoreENetworkStatus)getNetworkStatus;

- (void)startMonitoring;

- (void)stopMonitoring;

@end
