// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#import "CoreRAccount.h"
#import <Foundation/Foundation.h>

@interface CoreRAccountResponse : NSObject
- (nonnull instancetype)initWithAccessToken:(nonnull NSString *)accessToken
                               refreshToken:(nonnull NSString *)refreshToken
                                  expiresIn:(nullable NSNumber *)expiresIn
                                       user:(nonnull CoreRAccount *)user;
+ (nonnull instancetype)rAccountResponseWithAccessToken:(nonnull NSString *)accessToken
                                           refreshToken:(nonnull NSString *)refreshToken
                                              expiresIn:(nullable NSNumber *)expiresIn
                                                   user:(nonnull CoreRAccount *)user;

@property (nonatomic, readonly, nonnull) NSString * accessToken;

@property (nonatomic, readonly, nonnull) NSString * refreshToken;

@property (nonatomic, readonly, nullable) NSNumber * expiresIn;

@property (nonatomic, readonly, nonnull) CoreRAccount * user;

@end
