// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#import "CoreRGroupUpdateResponse.h"


@implementation CoreRGroupUpdateResponse

- (nonnull instancetype)initWithGroup:(nullable CoreRGroup *)group
{
    if (self = [super init]) {
        _group = group;
    }
    return self;
}

+ (nonnull instancetype)rGroupUpdateResponseWithGroup:(nullable CoreRGroup *)group
{
    return [[self alloc] initWithGroup:group];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p group:%@>", self.class, self, self.group];
}

@end
