// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_network_provider.djinni

#import "CoreRNetworkRequest+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto RNetworkRequest::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I64::toCpp(obj.requestID),
            ::djinni::String::toCpp(obj.host),
            ::djinni::String::toCpp(obj.path),
            ::djinni::Enum<::core_gen::ENetworkMethod, CoreENetworkMethod>::toCpp(obj.requestMethod),
            ::djinni::Map<::djinni::String, ::djinni::String>::toCpp(obj.header),
            ::djinni::String::toCpp(obj.data)};
}

auto RNetworkRequest::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[CoreRNetworkRequest alloc] initWithRequestID:(::djinni::I64::fromCpp(cpp.requestID))
                                                     host:(::djinni::String::fromCpp(cpp.host))
                                                     path:(::djinni::String::fromCpp(cpp.path))
                                            requestMethod:(::djinni::Enum<::core_gen::ENetworkMethod, CoreENetworkMethod>::fromCpp(cpp.request_method))
                                                   header:(::djinni::Map<::djinni::String, ::djinni::String>::fromCpp(cpp.header))
                                                     data:(::djinni::String::fromCpp(cpp.data))];
}

}  // namespace djinni_generated
