// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#import "CoreECallbackResult.h"
#import "CoreRGroup.h"
#import <Foundation/Foundation.h>


/**#create group */
@protocol CoreIGroupCallback

- (void)onGroupUpdated:(nonnull CoreRGroup *)group
                  code:(CoreECallbackResult)code;

@end
