// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#import <Foundation/Foundation.h>
@class CoreIContactUiController;
@class CoreIGroupCreateUiController;
@class CoreIGroupDetailUiController;
@class CoreIGroupMemberUiController;
@class CoreIGroupUiController;
@class CoreIGroupUpdateUiController;
@class CoreILifecycleUiController;
@class CoreILoginUiController;
@class CoreIProfileUiController;
@class CoreISignupUiController;
@protocol CoreILifecyleViewModelDelegate;
@protocol CoreIViewModelDelegate;


/**# factory */
@interface CoreIUiControllerFactory : NSObject

/** login */
- (nullable CoreILifecycleUiController *)createLifecycleUiController:(nullable id<CoreILifecyleViewModelDelegate>)delegate;

- (nullable CoreILoginUiController *)createLoginUiController:(nullable id<CoreIViewModelDelegate>)delegate;

- (nullable CoreISignupUiController *)createSignUpUiController:(nullable id<CoreIViewModelDelegate>)delegate;

/** contact */
- (nullable CoreIContactUiController *)createContactUiController:(nullable id<CoreIViewModelDelegate>)delegate;

/** group */
- (nullable CoreIGroupUiController *)createGroupUiController:(nullable id<CoreIViewModelDelegate>)delegate;

- (nullable CoreIGroupCreateUiController *)createGroupCreateUiController:(nullable id<CoreIViewModelDelegate>)delegate;

- (nullable CoreIGroupUpdateUiController *)createGroupUpdateUiController:(nullable id<CoreIViewModelDelegate>)delegate;

- (nullable CoreIGroupMemberUiController *)createGroupMemberUiController:(nullable id<CoreIViewModelDelegate>)delegate;

- (nullable CoreIGroupDetailUiController *)createGroupDetailUiController:(nullable id<CoreIViewModelDelegate>)delegate;

/** profiel */
- (nullable CoreIProfileUiController *)createProfileUiController:(nullable id<CoreIViewModelDelegate>)delegate;

@end
