// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#import "CoreListChange+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto ListChange::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.fromIndex),
            ::djinni::I32::toCpp(obj.toIndex)};
}

auto ListChange::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[CoreListChange alloc] initWithFromIndex:(::djinni::I32::fromCpp(cpp.from_index))
                                             toIndex:(::djinni::I32::fromCpp(cpp.to_index))];
}

}  // namespace djinni_generated
