// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#import "CoreIProfileUiController+Private.h"
#import "CoreIProfileUiController.h"
#import "CoreIActionCallback+Private.h"
#import "CoreIProfileViewModel+Private.h"
#import "CoreIRequestUploadTokenCallback+Private.h"
#import "CoreRAvatarInfo+Private.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#include <exception>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface CoreIProfileUiController ()

- (id)initWithCpp:(const std::shared_ptr<::core_gen::IProfileUiController>&)cppRef;

@end

@implementation CoreIProfileUiController {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::core_gen::IProfileUiController>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::core_gen::IProfileUiController>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (nullable CoreIProfileViewModel *)getViewModel {
    try {
        auto r = _cppRefHandle.get()->getViewModel();
        return ::djinni_generated::IProfileViewModel::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)updateAvatar:(nonnull CoreRAvatarInfo *)avatarInfo
            callback:(nullable id<CoreIActionCallback>)callback {
    try {
        _cppRefHandle.get()->updateAvatar(::djinni_generated::RAvatarInfo::toCpp(avatarInfo),
                                          ::djinni_generated::IActionCallback::toCpp(callback));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)requestUploadToken:(nullable id<CoreIRequestUploadTokenCallback>)callback {
    try {
        _cppRefHandle.get()->requestUploadToken(::djinni_generated::IRequestUploadTokenCallback::toCpp(callback));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)signout:(nullable id<CoreIActionCallback>)callback {
    try {
        _cppRefHandle.get()->signout(::djinni_generated::IActionCallback::toCpp(callback));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto IProfileUiController::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto IProfileUiController::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<CoreIProfileUiController>(cpp);
}

}  // namespace djinni_generated

@end
