// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#import "CoreRGroupUpdateResponse.h"
#include "r_group_update_response.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class CoreRGroupUpdateResponse;

namespace djinni_generated {

struct RGroupUpdateResponse
{
    using CppType = ::core_gen::RGroupUpdateResponse;
    using ObjcType = CoreRGroupUpdateResponse*;

    using Boxed = RGroupUpdateResponse;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
