// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_network_provider.djinni

#import "CoreRNetworkResponse+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto RNetworkResponse::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I64::toCpp(obj.code),
            ::djinni::Map<::djinni::String, ::djinni::List<::djinni::String>>::toCpp(obj.header),
            ::djinni::Enum<::core_gen::ERequestResult, CoreERequestResult>::toCpp(obj.status),
            ::djinni::Binary::toCpp(obj.data),
            ::djinni::String::toCpp(obj.contentType)};
}

auto RNetworkResponse::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[CoreRNetworkResponse alloc] initWithCode:(::djinni::I64::fromCpp(cpp.code))
                                               header:(::djinni::Map<::djinni::String, ::djinni::List<::djinni::String>>::fromCpp(cpp.header))
                                               status:(::djinni::Enum<::core_gen::ERequestResult, CoreERequestResult>::fromCpp(cpp.status))
                                                 data:(::djinni::Binary::fromCpp(cpp.data))
                                          contentType:(::djinni::String::fromCpp(cpp.content_type))];
}

}  // namespace djinni_generated
