// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_network_provider.djinni

#import "CoreENetworkStatus.h"
#import <Foundation/Foundation.h>


@interface CoreINetworkStatusDelegate : NSObject

- (void)onNetworkStatusChanged:(CoreENetworkStatus)status;

@end
