// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#import "CoreRGroup.h"
#import <Foundation/Foundation.h>
@class CoreIGroupMemberViewModel;
@protocol CoreIGroupCallback;


@interface CoreIGroupMemberUiController : NSObject

- (nullable CoreIGroupMemberViewModel *)getViewModel;

- (void)loadData:(nonnull CoreRGroup *)group;

- (void)addMembers:(nonnull NSArray<NSString *> *)memberIds
          callback:(nullable id<CoreIGroupCallback>)callback;

- (void)removeMembers:(nonnull NSArray<NSString *> *)memberIds
             callback:(nullable id<CoreIGroupCallback>)callback;

@end
