// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#import "CoreRAvatarDomain.h"


@implementation CoreRAvatarDomain

- (nonnull instancetype)initWithDomain:(nullable NSString *)domain
{
    if (self = [super init]) {
        _domain = [domain copy];
    }
    return self;
}

+ (nonnull instancetype)rAvatarDomainWithDomain:(nullable NSString *)domain
{
    return [[self alloc] initWithDomain:domain];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p domain:%@>", self.class, self, self.domain];
}

@end
