// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#import <Foundation/Foundation.h>

/** account */
typedef NS_ENUM(NSInteger, CoreELoginStatus)
{
    CoreELoginStatusInProgress,
    CoreELoginStatusInvalidCredentials,
    CoreELoginStatusSuccess,
    CoreELoginStatusFailure,
};
