// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#import "CoreRGroup.h"
#import <Foundation/Foundation.h>
@class CoreIGroupDetailViewModel;
@protocol CoreIActionCallback;


@interface CoreIGroupDetailUiController : NSObject

- (nullable CoreIGroupDetailViewModel *)getViewModel;

- (void)setGroup:(nonnull CoreRGroup *)group;

- (void)quit:(nullable id<CoreIActionCallback>)callback;

@end
