// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#import "CoreRGroupResponse+Private.h"
#import "CoreRGroup+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto RGroupResponse::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::Optional<std::experimental::optional, ::djinni::List<::djinni_generated::RGroup>>::toCpp(obj.groups)};
}

auto RGroupResponse::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[CoreRGroupResponse alloc] initWithGroups:(::djinni::Optional<std::experimental::optional, ::djinni::List<::djinni_generated::RGroup>>::fromCpp(cpp.groups))];
}

}  // namespace djinni_generated
