// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#import "CoreRUploadToken.h"
#include "r_upload_token.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class CoreRUploadToken;

namespace djinni_generated {

struct RUploadToken
{
    using CppType = ::core_gen::RUploadToken;
    using ObjcType = CoreRUploadToken*;

    using Boxed = RUploadToken;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
