// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#import "CoreRFutureError.h"
#include "r_future_error.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class CoreRFutureError;

namespace djinni_generated {

struct RFutureError
{
    using CppType = ::core_gen::RFutureError;
    using ObjcType = CoreRFutureError*;

    using Boxed = RFutureError;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
