// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#import "CoreRParsingError.h"
#include "r_parsing_error.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class CoreRParsingError;

namespace djinni_generated {

struct RParsingError
{
    using CppType = ::core_gen::RParsingError;
    using ObjcType = CoreRParsingError*;

    using Boxed = RParsingError;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
