// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#include "i_profile_view_model.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class CoreIProfileViewModel;

namespace djinni_generated {

class IProfileViewModel
{
public:
    using CppType = std::shared_ptr<::core_gen::IProfileViewModel>;
    using CppOptType = std::shared_ptr<::core_gen::IProfileViewModel>;
    using ObjcType = CoreIProfileViewModel*;

    using Boxed = IProfileViewModel;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

