// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#import "CoreIGroupCreateUiController+Private.h"
#import "CoreIGroupCreateUiController.h"
#import "CoreIGroupCallback+Private.h"
#import "CoreRContact+Private.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface CoreIGroupCreateUiController ()

- (id)initWithCpp:(const std::shared_ptr<::core_gen::IGroupCreateUiController>&)cppRef;

@end

@implementation CoreIGroupCreateUiController {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::core_gen::IGroupCreateUiController>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::core_gen::IGroupCreateUiController>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (void)createGroup:(nonnull NSArray<CoreRContact *> *)contacts
           callback:(nullable id<CoreIGroupCallback>)callback {
    try {
        _cppRefHandle.get()->createGroup(::djinni::List<::djinni_generated::RContact>::toCpp(contacts),
                                         ::djinni_generated::IGroupCallback::toCpp(callback));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto IGroupCreateUiController::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto IGroupCreateUiController::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<CoreIGroupCreateUiController>(cpp);
}

}  // namespace djinni_generated

@end
