// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#import "CoreRAccountResponse+Private.h"
#import "CoreRAccount+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto RAccountResponse::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.accessToken),
            ::djinni::String::toCpp(obj.refreshToken),
            ::djinni::Optional<std::experimental::optional, ::djinni::I32>::toCpp(obj.expiresIn),
            ::djinni_generated::RAccount::toCpp(obj.user)};
}

auto RAccountResponse::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[CoreRAccountResponse alloc] initWithAccessToken:(::djinni::String::fromCpp(cpp.access_token))
                                                refreshToken:(::djinni::String::fromCpp(cpp.refresh_token))
                                                   expiresIn:(::djinni::Optional<std::experimental::optional, ::djinni::I32>::fromCpp(cpp.expires_in))
                                                        user:(::djinni_generated::RAccount::fromCpp(cpp.user))];
}

}  // namespace djinni_generated
