// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, CoreEGroupMemberType)
{
    CoreEGroupMemberTypeMEMBER,
    CoreEGroupMemberTypeOWNER,
    CoreEGroupMemberTypeADMIN,
};
