// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#import "CoreRAvatarDomain+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto RAvatarDomain::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.domain)};
}

auto RAvatarDomain::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[CoreRAvatarDomain alloc] initWithDomain:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.domain))];
}

}  // namespace djinni_generated
