// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from model.djinni

#import <Foundation/Foundation.h>

@interface CoreRAccount : NSObject
- (nonnull instancetype)initWithUsername:(nullable NSString *)username
                                password:(nullable NSString *)password
                               grantType:(nullable NSString *)grantType
                                      id:(nullable NSString *)id
                                   email:(nullable NSString *)email
                               firstName:(nullable NSString *)firstName
                                lastName:(nullable NSString *)lastName
                             displayName:(nullable NSString *)displayName
                               companyId:(nullable NSString *)companyId
                          rongCloudToken:(nullable NSString *)rongCloudToken
                               avatarUrl:(nullable NSString *)avatarUrl;
+ (nonnull instancetype)rAccountWithUsername:(nullable NSString *)username
                                    password:(nullable NSString *)password
                                   grantType:(nullable NSString *)grantType
                                          id:(nullable NSString *)id
                                       email:(nullable NSString *)email
                                   firstName:(nullable NSString *)firstName
                                    lastName:(nullable NSString *)lastName
                                 displayName:(nullable NSString *)displayName
                                   companyId:(nullable NSString *)companyId
                              rongCloudToken:(nullable NSString *)rongCloudToken
                                   avatarUrl:(nullable NSString *)avatarUrl;

@property (nonatomic, readonly, nullable) NSString * username;

@property (nonatomic, readonly, nullable) NSString * password;

@property (nonatomic, readonly, nullable) NSString * grantType;

@property (nonatomic, readonly, nullable) NSString * id;

@property (nonatomic, readonly, nullable) NSString * email;

@property (nonatomic, readonly, nullable) NSString * firstName;

@property (nonatomic, readonly, nullable) NSString * lastName;

@property (nonatomic, readonly, nullable) NSString * displayName;

@property (nonatomic, readonly, nullable) NSString * companyId;

@property (nonatomic, readonly, nullable) NSString * rongCloudToken;

@property (nonatomic, readonly, nullable) NSString * avatarUrl;

@end

extern NSString * __nonnull const CoreRAccountGRANDTYPEPASSWORD;
