// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from view_model.djinni

#import "CoreIActionCallback+Private.h"
#import "CoreIActionCallback.h"
#import "CoreRActionResult+Private.h"
#import "DJIObjcWrapperCache+Private.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class IActionCallback::ObjcProxy final
: public ::core_gen::IActionCallback
, public ::djinni::ObjcProxyCache::Handle<ObjcType>
{
public:
    using Handle::Handle;
    void onResponse(const ::core_gen::RActionResult & c_result) override
    {
        @autoreleasepool {
            [Handle::get() onResponse:(::djinni_generated::RActionResult::fromCpp(c_result))];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto IActionCallback::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto IActionCallback::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).Handle::get();
}

}  // namespace djinni_generated
