// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#import "CoreRNetworkError+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto RNetworkError::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.errorCode)};
}

auto RNetworkError::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[CoreRNetworkError alloc] initWithErrorCode:(::djinni::I32::fromCpp(cpp.error_code))];
}

}  // namespace djinni_generated
