// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#import "CoreRIntegerIdError+Private.h"
#import "CoreRFutureError+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto RIntegerIdError::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I64::toCpp(obj.id),
            ::djinni_generated::RFutureError::toCpp(obj.error)};
}

auto RIntegerIdError::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[CoreRIntegerIdError alloc] initWithId:(::djinni::I64::fromCpp(cpp.id))
                                             error:(::djinni_generated::RFutureError::fromCpp(cpp.error))];
}

}  // namespace djinni_generated
